CREATE TABLE [EncounterModule].[Service] (
    [ServiceKey]                                BIGINT             NOT NULL,
    [Version]                                   INT                NOT NULL,
    [TrackingNumber]                            BIGINT             NOT NULL,
    [PrimaryIndicator]                          BIT                NOT NULL,
    [CreatedTimestamp]                          DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                          DATETIMEOFFSET (7) NOT NULL,
    [EncounterKey]                              BIGINT             NULL,
    [CreatedBySystemAccountKey]                 BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                 BIGINT             NOT NULL,
    [ProcedureCodeCodedConceptCode]             NVARCHAR (10)      NULL,
    [ProcedureCodeDisplayName]                  NVARCHAR (100)     NULL,
    [ProcedureCodeCodeSystemIdentifier]         NVARCHAR (50)      NULL,
    [ProcedureCodeCodeSystemVersionNumber]      NVARCHAR (20)      NULL,
    [ProcedureCodeCodeSystemName]               NVARCHAR (100)     NULL,
    [ProcedureCodeOriginalDescription]          NVARCHAR (500)     NULL,
    [ProcedureCodeNullFlavorIndicator]          BIT                NULL,
    [FirstModifierCodeCodedConceptCode]         NVARCHAR (10)      NULL,
    [FirstModifierCodeDisplayName]              NVARCHAR (100)     NULL,
    [FirstModifierCodeCodeSystemIdentifier]     NVARCHAR (50)      NULL,
    [FirstModifierCodeCodeSystemVersionNumber]  NVARCHAR (20)      NULL,
    [FirstModifierCodeCodeSystemName]           NVARCHAR (100)     NULL,
    [FirstModifierCodeOriginalDescription]      NVARCHAR (500)     NULL,
    [FirstModifierCodeNullFlavorIndicator]      BIT                NULL,
    [SecondModifierCodeCodedConceptCode]        NVARCHAR (10)      NULL,
    [SecondModifierCodeDisplayName]             NVARCHAR (100)     NULL,
    [SecondModifierCodeCodeSystemIdentifier]    NVARCHAR (50)      NULL,
    [SecondModifierCodeCodeSystemVersionNumber] NVARCHAR (20)      NULL,
    [SecondModifierCodeCodeSystemName]          NVARCHAR (100)     NULL,
    [SecondModifierCodeOriginalDescription]     NVARCHAR (500)     NULL,
    [SecondModifierCodeNullFlavorIndicator]     BIT                NULL,
    [ThirdModifierCodeCodedConceptCode]         NVARCHAR (10)      NULL,
    [ThirdModifierCodeDisplayName]              NVARCHAR (100)     NULL,
    [ThirdModifierCodeCodeSystemIdentifier]     NVARCHAR (50)      NULL,
    [ThirdModifierCodeCodeSystemVersionNumber]  NVARCHAR (20)      NULL,
    [ThirdModifierCodeCodeSystemName]           NVARCHAR (100)     NULL,
    [ThirdModifierCodeOriginalDescription]      NVARCHAR (500)     NULL,
    [ThirdModifierCodeNullFlavorIndicator]      BIT                NULL,
    [FourthModifierCodeCodedConceptCode]        NVARCHAR (10)      NULL,
    [FourthModifierCodeDisplayName]             NVARCHAR (100)     NULL,
    [FourthModifierCodeCodeSystemIdentifier]    NVARCHAR (50)      NULL,
    [FourthModifierCodeCodeSystemVersionNumber] NVARCHAR (20)      NULL,
    [FourthModifierCodeCodeSystemName]          NVARCHAR (100)     NULL,
    [FourthModifierCodeOriginalDescription]     NVARCHAR (500)     NULL,
    [FourthModifierCodeNullFlavorIndicator]     BIT                NULL,
    [RatePerBillingUnitAmount]                  DECIMAL (19, 5)    NULL,
    [RatePerBillingUnitCurrencyLkpKey]          BIGINT             NULL,
    [DiagnosisCodedConceptCode]                 NVARCHAR (10)      NULL,
    [DiagnosisDisplayName]                      NVARCHAR (100)     NULL,
    [DiagnosisCodeSystemIdentifier]             NVARCHAR (50)      NULL,
    [DiagnosisCodeSystemVersionNumber]          NVARCHAR (20)      NULL,
    [DiagnosisCodeSystemName]                   NVARCHAR (100)     NULL,
    [DiagnosisOriginalDescription]              NVARCHAR (500)     NULL,
    [DiagnosisNullFlavorIndicator]              BIT                NULL,
    [ChargeAmountAmount]                        DECIMAL (19, 5)    NULL,
    [ChargeAmountCurrencyLkpKey]                BIGINT             NULL,
    [BillingCount]                              SMALLINT           NULL,
    PRIMARY KEY CLUSTERED ([ServiceKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





