
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_CollegeDegreeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 100, current_timestamp, 1, current_timestamp, 1, 1,   N'MD', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 101, current_timestamp, 1, current_timestamp, 1, 1,  N'PhD', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 102, current_timestamp, 1, current_timestamp, 1, 1, N'PsyD', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 103, current_timestamp, 1, current_timestamp, 1, 1,   N'AA', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 104, current_timestamp, 1, current_timestamp, 1, 1,   N'BA', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 105, current_timestamp, 1, current_timestamp, 1, 1,   N'MS', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 106, current_timestamp, 1, current_timestamp, 1, 1,   N'DO', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[CollegeDegreeLkp] ( [CollegeDegreeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 107, current_timestamp, 1, current_timestamp, 1, 1,   N'BS', NULL, NULL, NULL, NULL, '3/31/2011', NULL, 0, 0 )

GO
