
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_AgencyAddressTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[AgencyAddressTypeLkp] ( [AgencyAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5695326, current_timestamp, 1, current_timestamp, 1, 0, N'Administration', NULL, N'Administration', N'OFC', 0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyAddressTypeLkp] ( [AgencyAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7752229, current_timestamp, 1, current_timestamp, 1, 0,        N'Billing', NULL,        N'Billing', N'BIL', 0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyAddressTypeLkp] ( [AgencyAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7752230, current_timestamp, 1, current_timestamp, 1, 0,       N'Physical', NULL,       N'Physical', N'PHY', 0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyAddressTypeLkp] ( [AgencyAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7752231, current_timestamp, 1, current_timestamp, 1, 0,        N'Mailing', NULL,        N'Mailing', N'MIL', 0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyAddressTypeLkp] ( [AgencyAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7752232, current_timestamp, 1, current_timestamp, 1, 0,       N'Shipping', NULL,       N'Shipping', N'SHP', 0, '1/1/1900', NULL, 0, 0 )

GO
