
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_StaffTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 100, current_timestamp, 1, current_timestamp, 1, 0,           N'Clinician', NULL, N'Cli', N'Cli', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 101, current_timestamp, 1, current_timestamp, 1, 0,      N'Administration', NULL, N'Adm', N'Adm', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 102, current_timestamp, 1, current_timestamp, 1, 0,      N'Student Intern', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 103, current_timestamp, 1, current_timestamp, 1, 0,    N'Agency Executive', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 104, current_timestamp, 1, current_timestamp, 1, 0,  N'State Fiscal Staff', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 105, current_timestamp, 1, current_timestamp, 1, 0,               N'Judge', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 106, current_timestamp, 1, current_timestamp, 1, 0, N'Clinical Supervisor', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 107, current_timestamp, 1, current_timestamp, 1, 0,       N'Staff Manager', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffTypeLkp] ( [StaffTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 108, current_timestamp, 1, current_timestamp, 1, 0,             N'Billing', NULL, N'Int', N'Int', NULL, '3/31/2011', NULL, 0, 0 )

GO
