
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_StaffChecklistItemTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[StaffChecklistItemTypeLkp] ( [StaffChecklistItemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374637, current_timestamp, 1, current_timestamp, 1, 0,             N'Performance Appraisal Participation',             N'Performance Appraisal Participation', NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffChecklistItemTypeLkp] ( [StaffChecklistItemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374638, current_timestamp, 1, current_timestamp, 1, 0, N'Policies and Procedure Manual has been reviewed', N'Policies and Procedure Manual has been reviewed', NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffChecklistItemTypeLkp] ( [StaffChecklistItemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374639, current_timestamp, 1, current_timestamp, 1, 0,        N'Required Background checks are completed',        N'Required Background checks are completed', NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[StaffChecklistItemTypeLkp] ( [StaffChecklistItemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374640, current_timestamp, 1, current_timestamp, 1, 0,          N'Background check outcome is acceptable',          N'Background check outcome is acceptable', NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )

GO
