
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_AgencyContactTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374637, current_timestamp, 1, current_timestamp, 1, 1,                        N'Billing', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374638, current_timestamp, 1, current_timestamp, 1, 1,                            N'EDI', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374639, current_timestamp, 1, current_timestamp, 1, 1, N'Fiscal/Contract Administration', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374640, current_timestamp, 1, current_timestamp, 1, 1,                      N'Executive', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374641, current_timestamp, 1, current_timestamp, 1, 1,       N'Board of Director Member', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374642, current_timestamp, 1, current_timestamp, 1, 1,                            N'CEO', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374643, current_timestamp, 1, current_timestamp, 1, 1,                        N'Primary', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyContactTypeLkp] ( [AgencyContactTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374644, current_timestamp, 1, current_timestamp, 1, 1,                      N'Secondary', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )

GO
