
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_AgencyTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 100, current_timestamp, 1, current_timestamp, 1, 0,                 N'Treatment Provider', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 101, current_timestamp, 1, current_timestamp, 1, 0,                   N'Criminal Justice', NULL, NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 102, current_timestamp, 1, current_timestamp, 1, 0,                N'Single State Agency', NULL, NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 103, current_timestamp, 1, current_timestamp, 1, 0, N'Recovery Support Services Provider', NULL, NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 104, current_timestamp, 1, current_timestamp, 1, 0,              N'System Testing Agency', NULL, NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyTypeLkp] ( [AgencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 105, current_timestamp, 1, current_timestamp, 1, 0,                       N'State Agency', NULL, NULL, NULL,    0, '1/1/1900', NULL, 0, 0 )

GO
