
print '------------------------------------------------------------------------------------------'
print 'AgencyModule_AgencyIdentifierTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [AgencyModule].[AgencyIdentifierTypeLkp] ( [AgencyIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374637, current_timestamp, 1, current_timestamp, 1, 0,              N'NPI', NULL,                 N'Npi', NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyIdentifierTypeLkp] ( [AgencyIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374638, current_timestamp, 1, current_timestamp, 1, 0,   N'Federal Tax ID', NULL,        N'FederalTaxId', NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyIdentifierTypeLkp] ( [AgencyIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374639, current_timestamp, 1, current_timestamp, 1, 0,        N'License #', NULL,       N'LicenseNumber', NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyIdentifierTypeLkp] ( [AgencyIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374640, current_timestamp, 1, current_timestamp, 1, 0,           N'Site #', NULL,          N'SiteNumber', NULL, NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [AgencyModule].[AgencyIdentifierTypeLkp] ( [AgencyIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2374641, current_timestamp, 1, current_timestamp, 1, 0, N'State Business #', NULL, N'StateBusinessNumber', NULL, NULL, '1/1/1900', NULL, 0, 0 )

GO
