print '------------------------------------------------------------------------------------------'
print 'BillingOfficeModule_BillingOfficePhoneTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [BillingOfficeModule].[BillingOfficePhoneTypeLkp] ( [BillingOfficePhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3511169, current_timestamp, 1, current_timestamp, 1, 0, N'Customer Service', NULL, N'OTH', N'OTH', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [BillingOfficeModule].[BillingOfficePhoneTypeLkp] ( [BillingOfficePhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5983855, current_timestamp, 1, current_timestamp, 1, 0,  N'Main Line', NULL,   N'ML',   N'ML',    2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [BillingOfficeModule].[BillingOfficePhoneTypeLkp] ( [BillingOfficePhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6911176, current_timestamp, 1, current_timestamp, 1, 0,   N'Fax', NULL,   N'F',   N'F',    4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [BillingOfficeModule].[BillingOfficePhoneTypeLkp] ( [BillingOfficePhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8480151, current_timestamp, 1, current_timestamp, 1, 0,  N'Toll Free Number', NULL,   N'TF',   N'TF',    3, '1/1/1900',        NULL, 0, 0 )
																																																																																					 
GO