
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_ProblemTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         2, current_timestamp, 1, current_timestamp, 1, 0,               N'Finding', NULL,   N'Finding',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0, N'404684003' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         3, current_timestamp, 1, current_timestamp, 1, 0,               N'Symptom', NULL,   N'Symptom',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0, N'418799008' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         4, current_timestamp, 1, current_timestamp, 1, 0,             N'Complaint', NULL, N'Complaint',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0, N'409586006' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         5, current_timestamp, 1, current_timestamp, 1, 0,               N'Disease', NULL,   N'Disease',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0,  N'64572001' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         6, current_timestamp, 1, current_timestamp, 1, 0,             N'Diagnosis', NULL, N'Diagnosis',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0, N'282291009' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES (         7, current_timestamp, 1, current_timestamp, 1, 0, N'Functional limitation', NULL,  N'FunctLim',   NULL, NULL,  '1/1/2011',  '1/1/2011', 0, 0, N'248536006' )
INSERT INTO [ClinicalCaseModule].[ProblemTypeLkp] ( [ProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 919366788, current_timestamp, 1, current_timestamp, 1, 0,               N'Problem', NULL,       N'DIA', N'DIA', NULL, '6/11/2010', '6/11/2010', 0, 0,  N'55607006' )

GO
