
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_InitialContactMethodLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2156123, current_timestamp, 1, current_timestamp, 1, 0,                  N'By Appointment',                  N'By Appointment', N'A', N'A', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3351913, current_timestamp, 1, current_timestamp, 1, 0,                         N'Walk-in',                         N'Walk-in', N'W', N'W', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4821315, current_timestamp, 1, current_timestamp, 1, 0, N'Emergency Outreach Intervention', N'Emergency Outreach Intervention', N'E', N'E', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7221270, current_timestamp, 1, current_timestamp, 1, 0,                           N'Phone',                           N'Phone', N'P', N'P', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7452187, current_timestamp, 1, current_timestamp, 1, 0,        N'Community service patrol',        N'Community service patrol', N'C', N'C', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9328623, current_timestamp, 1, current_timestamp, 1, 0,   N'Hospital/On-Call Intervention',   N'Hospital/On-Call Intervention', N'H', N'H', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[InitialContactMethodLkp] ( [InitialContactMethodLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9803181, current_timestamp, 1, current_timestamp, 1, 0,                           N'Other',                           N'Other', N'O', N'O', NULL, '1/1/1900', NULL, 0, 0 )

GO
