
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_ReferralTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  224599, current_timestamp, 1, current_timestamp, 1, 0,                       N'DOH-Adult Mental Health Division',                       N'DOH-Adult Mental Health Division',  N'DOHA',  N'DOHA', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  484618, current_timestamp, 1, current_timestamp, 1, 0,          N'DOH-Child & Adolescent Mental Health Division',          N'DOH-Child & Adolescent Mental Health Division',  N'DOHC',  N'DOHC', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  749774, current_timestamp, 1, current_timestamp, 1, 0,                               N'Other Community Referral',                               N'Other Community Referral',   N'OCR',   N'OCR', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  991301, current_timestamp, 1, current_timestamp, 1, 0,                                N'Criminal Justice-Parole',                                N'Criminal Justice-Parole',   N'CJR',   N'CJR', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1019990, current_timestamp, 1, current_timestamp, 1, 0,                           N'Child Welfare Services (CWS)',                           N'Child Welfare Services (CWS)',   N'CWS',   N'CWS', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1319749, current_timestamp, 1, current_timestamp, 1, 0, N'Criminal Justice-Judiciary/Drug & Other Special Courts', N'Criminal Justice-Judiciary/Drug & Other Special Courts',   N'CJJ',   N'CJJ', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1387033, current_timestamp, 1, current_timestamp, 1, 0,                            N'Alcohol/Drug Abuse Provider',                            N'Alcohol/Drug Abuse Provider',   N'ADA',   N'ADA', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1466430, current_timestamp, 1, current_timestamp, 1, 0,                               N'Criminal Justice-DUI/DWI',                               N'Criminal Justice-DUI/DWI', N'CJDUI', N'CJDUI', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1541817, current_timestamp, 1, current_timestamp, 1, 0,                                          N'Employer/EAPs',                                          N'Employer/EAPs',   N'EAP',   N'EAP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1564647, current_timestamp, 1, current_timestamp, 1, 0,                                          N'Parent/Family',                                          N'Parent/Family',    N'PF',    N'PF', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2264477, current_timestamp, 1, current_timestamp, 1, 0,                                      N'Family Drug Court',                                      N'Family Drug Court',   N'FDC',   N'FDC', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2332639, current_timestamp, 1, current_timestamp, 1, 0,                   N'Criminal Justice-State/Federal Court',                   N'Criminal Justice-State/Federal Court',   N'CJS',   N'CJS', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2537530, current_timestamp, 1, current_timestamp, 1, 0,                                      N'Individual (self)',                                      N'Individual (self)',   N'IND',   N'IND', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2791997, current_timestamp, 1, current_timestamp, 1, 0,     N'Dept. of Public Safety-Intake Service Center (ISC)',     N'Dept. of Public Safety-Intake Service Center (ISC)',   N'DPF',   N'DPF', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2867457, current_timestamp, 1, current_timestamp, 1, 0,     N'Criminal Justice-Other Formal Adjudication Process',     N'Criminal Justice-Other Formal Adjudication Process',  N'CJOF',  N'CJOF', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2999915, current_timestamp, 1, current_timestamp, 1, 0,                             N'Other Health Care Provider',                             N'Other Health Care Provider',   N'OHP',   N'OHP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3061926, current_timestamp, 1, current_timestamp, 1, 0,         N'Criminal Justice-Other Recognized Legal Entity',         N'Criminal Justice-Other Recognized Legal Entity',  N'CJOR',  N'CJOR', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3123577, current_timestamp, 1, current_timestamp, 1, 0,                                 N'Criminal Justice-Other',                                 N'Criminal Justice-Other',   N'CJO',   N'CJO', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3177807, current_timestamp, 1, current_timestamp, 1, 0,                                N'Criminal Justice-Prison',                                N'Criminal Justice-Prison',   N'CJP',   N'CJP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3256961, current_timestamp, 1, current_timestamp, 1, 0,                   N'Criminal Justice-Judiciary/Probation',                   N'Criminal Justice-Judiciary/Probation',  N'CJJP',  N'CJJP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3466628, current_timestamp, 1, current_timestamp, 1, 0,                      N'Criminal Justice-Probation/Parole',                      N'Criminal Justice-Probation/Parole',  N'CJPP',  N'CJPP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3584517, current_timestamp, 1, current_timestamp, 1, 0,                                                  N'Quest',                                                  N'Quest',   N'QUS',   N'QUS', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3891477, current_timestamp, 1, current_timestamp, 1, 0,                                   N'School (Educational)',                                   N'School (Educational)',   N'SCH',   N'SCH', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4129921, current_timestamp, 1, current_timestamp, 1, 0,             N'Criminal Justice-Diversionary Program/TASC',             N'Criminal Justice-Diversionary Program/TASC',  N'CJDP',  N'CJDP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ReferralTypeLkp] ( [ReferralTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4740268, current_timestamp, 1, current_timestamp, 1, 0,                                                N'Unknown',                                                N'Unknown',    N'UN',    N'UN', NULL, '1/1/1900',        NULL, 0, 0 )

GO
