
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_SpecialInitiativeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[SpecialInitiativeLkp] ( [SpecialInitiativeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  174697, current_timestamp, 1, current_timestamp, 1, 0, N'Consented to participate in research', N'Consented to participate in research', N'CPR', N'CPR', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[SpecialInitiativeLkp] ( [SpecialInitiativeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  616137, current_timestamp, 1, current_timestamp, 1, 0,             N'Buprenorphine Initiative',             N'Buprenorphine Initiative',  N'BI',  N'BI', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[SpecialInitiativeLkp] ( [SpecialInitiativeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2157621, current_timestamp, 1, current_timestamp, 1, 0,                     N'Katrina affected',                     N'Katrina affected',  N'KA',  N'KA', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[SpecialInitiativeLkp] ( [SpecialInitiativeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4916232, current_timestamp, 1, current_timestamp, 1, 0,                N'BP Oil Spill affected',                N'BP Oil Spill affected', N'BPO', N'BPO', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[SpecialInitiativeLkp] ( [SpecialInitiativeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5148167, current_timestamp, 1, current_timestamp, 1, 0,                    N'Military Veterans',                    N'Military Veterans',  N'MV',  N'MV', NULL, '1/1/1900',        NULL, 0, 0 )

GO
