
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_PriorityPopulationLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[PriorityPopulationLkp] ( [PriorityPopulationLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 258420, current_timestamp, 1, current_timestamp, 1, 0, N'Child/Youth with Severe Emotional Disturbance', N'Child/Youth with Severe Emotional Disturbance', N'CYS', N'CYS', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[PriorityPopulationLkp] ( [PriorityPopulationLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 637560, current_timestamp, 1, current_timestamp, 1, 0,                           N'Injection Drug User',                           N'Injection Drug User', N'IDU', N'IDU', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[PriorityPopulationLkp] ( [PriorityPopulationLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 637564, current_timestamp, 1, current_timestamp, 1, 0,                              N'Women w/Children',                              N'Women w/Children',  N'WC',  N'WC', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[PriorityPopulationLkp] ( [PriorityPopulationLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 787050, current_timestamp, 1, current_timestamp, 1, 0,                            N'Returning Veterans',                            N'Returning Veterans',  N'RV',  N'RV', NULL, '1/1/1900', NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[PriorityPopulationLkp] ( [PriorityPopulationLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 787070, current_timestamp, 1, current_timestamp, 1, 0,                             N'Suicide – At Risk',                             N'Suicide – At Risk', N'SAR', N'SAR', NULL, '1/1/1900', NULL, 0, 0 )

GO
