
print '------------------------------------------------------------------------------------------'
print 'ClinicalCaseModule_ClinicalCaseStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  258420, current_timestamp, 1, current_timestamp, 1, 0,      N'Case Initiation',      N'Case Initiation',     N'CaseInitiation', N'CI', 1, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  637564, current_timestamp, 1, current_timestamp, 1, 0, N'Admission in Process', N'Admission in Process', N'AdmissionInProcess', N'AP', 2, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  787050, current_timestamp, 1, current_timestamp, 1, 0,  N'Active/In Treatment',  N'Active/In Treatment',             N'Active', N'AT', 3, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  787060, current_timestamp, 1, current_timestamp, 1, 0,           N'Discharged',           N'Discharged',         N'Discharged', N'DS', 5, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5042490, current_timestamp, 1, current_timestamp, 1, 0,               N'Closed',               N'Closed',             N'Closed', N'CL', 6, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [ClinicalCaseModule].[ClinicalCaseStatusLkp] ( [ClinicalCaseStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5042492, current_timestamp, 1, current_timestamp, 1, 0, N'Discharge in Process', N'Discharge in Process', N'DischargeInProcess', N'DP', 4, '1/1/1900',       NULL, 0, 0 )

GO
