
print '------------------------------------------------------------------------------------------'
print 'CommonModule_CurrencyLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (184246,  current_timestamp, 1, current_timestamp, 1, 0,       N'United States Dollar', NULL, N'USD', N'USD', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (625118,  current_timestamp, 1, current_timestamp, 1, 0,      N'Euro Member Countries', NULL, N'EUR', N'EUR', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (950945,  current_timestamp, 1, current_timestamp, 1, 0,       N'United Kingdom Pound', NULL, N'GBP', N'GBP', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (1170521, current_timestamp, 1, current_timestamp, 1, 0,           N'Australia Dollar', NULL, N'AUD', N'AUD', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (1612396, current_timestamp, 1, current_timestamp, 1, 0,              N'Canada Dollar', NULL, N'CAD', N'CAD', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (1720626, current_timestamp, 1, current_timestamp, 1, 0,                  N'Japan Yen', NULL, N'YEN', N'YEN', '19000101', NULL, 0, 0, 0, N'en-US')
INSERT INTO [CommonModule].[CurrencyLkp] ([CurrencyLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CultureName]) VALUES (1742257, current_timestamp, 1, current_timestamp, 1, 0,         N'New Zealand Dollar', NULL, N'NZD', N'NZD', '19000101', NULL, 0, 0, 0, N'en-US')



GO

