
print '------------------------------------------------------------------------------------------'
print 'CommonModule_CountyAreaLkp'
print '------------------------------------------------------------------------------------------'

INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (232455,  current_timestamp, 1, current_timestamp, 1, 0, N'Howard',           NULL, N'027', N'027', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (374199,  current_timestamp, 1, current_timestamp, 1, 0, N'Kent',             NULL, N'029', N'029', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (595452,  current_timestamp, 1, current_timestamp, 1, 0, N'Dorchester',       NULL, N'019', N'019', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (1511039, current_timestamp, 1, current_timestamp, 1, 0, N'Talbot',           NULL, N'041', N'041', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (1527368, current_timestamp, 1, current_timestamp, 1, 0, N'Harford',          NULL, N'025', N'025', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (2852185, current_timestamp, 1, current_timestamp, 1, 0, N'Caroline',         NULL, N'011', N'011', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (3348633, current_timestamp, 1, current_timestamp, 1, 0, N'Prince George''s', NULL, N'033', N'033', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (3817361, current_timestamp, 1, current_timestamp, 1, 0, N'Anne Arundel',     NULL, N'003', N'003', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (3906243, current_timestamp, 1, current_timestamp, 1, 0, N'Queen Anne''s',    NULL, N'035', N'035', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (4444193, current_timestamp, 1, current_timestamp, 1, 0, N'Allegany',         NULL, N'001', N'001', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (4604573, current_timestamp, 1, current_timestamp, 1, 0, N'Cecil',            NULL, N'015', N'015', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (4964796, current_timestamp, 1, current_timestamp, 1, 0, N'Frederick',        NULL, N'021', N'021', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (5422740, current_timestamp, 1, current_timestamp, 1, 0, N'Carroll',          NULL, N'013', N'013', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (5429075, current_timestamp, 1, current_timestamp, 1, 0, N'Montgomery',       NULL, N'031', N'031', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (6401638, current_timestamp, 1, current_timestamp, 1, 0, N'Washington',       NULL, N'043', N'043', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (6598496, current_timestamp, 1, current_timestamp, 1, 0, N'Somerset',         NULL, N'039', N'039', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (6745716, current_timestamp, 1, current_timestamp, 1, 0, N'St. Mary''s',      NULL, N'037', N'037', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (7157045, current_timestamp, 1, current_timestamp, 1, 0, N'Garrett',          NULL, N'023', N'023', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (7397463, current_timestamp, 1, current_timestamp, 1, 0, N'Wicomico',         NULL, N'045', N'045', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (7515238, current_timestamp, 1, current_timestamp, 1, 0, N'Calvert',          NULL, N'009', N'009', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (9364630, current_timestamp, 1, current_timestamp, 1, 0, N'Charles',          NULL, N'017', N'017', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (9421285, current_timestamp, 1, current_timestamp, 1, 0, N'Baltimore',        NULL, N'005', N'005', '19000101', NULL, 0, 0, 0, 5409183)
INSERT INTO [CommonModule].[CountyAreaLkp] ([CountyAreaLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [StateProvinceLkpKey]) VALUES (9600383, current_timestamp, 1, current_timestamp, 1, 0, N'Worcester',        NULL, N'047', N'047', '19000101', NULL, 0, 0, 0, 5409183)


GO

