
print '------------------------------------------------------------------------------------------'
print 'CommonModule_PrefixLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [CommonModule].[PrefixLkp] ( [PrefixLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2270182, current_timestamp, 1, current_timestamp, 1, 0,  N'Ms.', N'a title of respect prefixed to a woman''''s name or position: unlike Miss  or Mrs.,  it does not depend upon or indicate her marital status.',  N'Ms.',  N'Ms.', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[PrefixLkp] ( [PrefixLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5728771, current_timestamp, 1, current_timestamp, 1, 0,  N'Mr.',                                                                                   N'a title of respect prefixed to a man''''s name or position',  N'Mr.',  N'Mr.', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[PrefixLkp] ( [PrefixLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7933879, current_timestamp, 1, current_timestamp, 1, 0, N'Mrs.',                                                                                   N'a title of respect prefixed to the name of a married woman', N'Mrs.', N'Mrs.', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[PrefixLkp] ( [PrefixLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7933880, current_timestamp, 1, current_timestamp, 1, 0,  N'Dr.',                                                                                          N'a title of respect prefixed to the name of a doctor',  N'Dr.',  N'Dr.', NULL, '1/1/1900',        NULL, 0, 0 )

GO
