
print '------------------------------------------------------------------------------------------'
print 'CommonModule_GeographicalRegionLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  254861, current_timestamp, 1, current_timestamp, 1, 0,     N'Northeast Region', NULL, N'NE', N'NE', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  804016, current_timestamp, 1, current_timestamp, 1, 0, N'South Central Region', NULL, N'SC', N'SC', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1183319, current_timestamp, 1, current_timestamp, 1, 0,     N'Southeast Region', NULL, N'SE', N'SE', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2298295, current_timestamp, 1, current_timestamp, 1, 0,       N'Western Region', NULL, N'WT', N'WT', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2711394, current_timestamp, 1, current_timestamp, 1, 0,           N'District 1', NULL, N'D1', N'D1', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6307341, current_timestamp, 1, current_timestamp, 1, 0,           N'District 2', NULL, N'D2', N'D2', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6673485, current_timestamp, 1, current_timestamp, 1, 0,           N'District 3', NULL, N'D3', N'D3', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [CommonModule].[GeographicalRegionLkp] ( [GeographicalRegionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9545312, current_timestamp, 1, current_timestamp, 1, 0,           N'District 4', NULL, N'D4', N'D4', 2, '1/1/1900',        NULL, 0, 0 )

GO
