
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiViolationTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  1, current_timestamp, 1, current_timestamp, 1, 0,                                       N'Shoplifting/Vandalism',                                       N'Shoplifting/Vandalism', N'SV', N'SV',  1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  2, current_timestamp, 1, current_timestamp, 1, 0,                                 N'Parole/Probation Violations',                                 N'Parole/Probation Violations', N'PP', N'PP',  2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  3, current_timestamp, 1, current_timestamp, 1, 0,                                                N'Drug Charges',                                                N'Drug Charges', N'DC', N'DC',  3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  4, current_timestamp, 1, current_timestamp, 1, 0,                                                     N'Forgery',                                                     N'Forgery', N'FG', N'FG',  4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  5, current_timestamp, 1, current_timestamp, 1, 0,                                             N'Weapons Offense',                                             N'Weapons Offense', N'WO', N'WO',  5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  6, current_timestamp, 1, current_timestamp, 1, 0,                                        N'Burglary/Larceny/B&E',                                        N'Burglary/Larceny/B&E', N'BL', N'BL',  6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  7, current_timestamp, 1, current_timestamp, 1, 0,                                                     N'Robbery',                                                     N'Robbery', N'RB', N'RB',  7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  8, current_timestamp, 1, current_timestamp, 1, 0,                                                     N'Assault',                                                     N'Assault', N'AS', N'AS',  8, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  9, current_timestamp, 1, current_timestamp, 1, 0,                                                       N'Arson',                                                       N'Arson', N'AR', N'AR',  9, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 0,                                         N'Rape/Attempted Rape',                                         N'Rape/Attempted Rape', N'RA', N'RA', 10, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 0,                    N'Homicide/Manslaughter/Attempted Homicide',                    N'Homicide/Manslaughter/Attempted Homicide', N'HM', N'HM', 11, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 0,                                                N'Prostitution',                                                N'Prostitution', N'PR', N'PR', 12, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 0,                                           N'Contempt of Court',                                           N'Contempt of Court', N'CC', N'CC', 13, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 14, current_timestamp, 1, current_timestamp, 1, 0,                                                       N'Other',                                                       N'Other', N'OT', N'OT', 14, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 15, current_timestamp, 1, current_timestamp, 1, 0,           N'Disorderly Conduct, Vagrancy, Public Intoxication',           N'Disorderly Conduct, Vagrancy, Public Intoxication', N'DV', N'DV', 15, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 16, current_timestamp, 1, current_timestamp, 1, 0,                                   N'Driving While Intoxicated',                                   N'Driving While Intoxicated', N'DI', N'DI', 16, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiViolationTypeLkp] ( [DensAsiViolationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 17, current_timestamp, 1, current_timestamp, 1, 0, N'Major Driving Violations (Reckless, Speeding, No Lic, Etc.)', N'Major Driving Violations (Reckless, Speeding, No Lic, Etc.)', N'MD', N'MD', 17, '1/1/1900', NULL, 0, 0 )

GO
