
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiEmploymentPatternLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,       N'Full Time (35+ Hours)',              N'Full Time',  N'FT',  N'FT', 1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,   N'Part Time (Regular Hours)',      N'Part Time Regular', N'PTR', N'PTR', 2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Part Time (Irregular Hours)',    N'Part Time Irregular', N'PTI', N'PTI', 3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,                     N'Student',                N'Student',  N'ST',  N'ST', 4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,          N'Service (Military)',                N'Service',  N'SM',  N'SM', 5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,          N'Retired/Disability',     N'Retired/Disability',  N'RD',  N'RD', 6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0,                  N'Unemployed',             N'Unemployed',  N'UN',  N'UN', 7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiEmploymentPatternLkp] ( [DensAsiEmploymentPatternLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0,   N'In Controlled Environment', N'Controlled Environment',  N'CE',  N'CE', 8, '1/1/1900', NULL, 0, 0 )

GO
