
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiControlledEnvironmentLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,                      N'No',                      N'No', N'N', N'N', 1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,                    N'Jail',                    N'Jail', N'J', N'J', 2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Alcohol/ Drug Treatment', N'Alcohol/ Drug Treatment', N'A', N'A', 3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,       N'Medical Treatment',       N'Medical Treatment', N'M', N'M', 4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,   N'Psychiatric Treatment',   N'Psychiatric Treatment', N'P', N'P', 5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiControlledEnvironmentLkp] ( [DensAsiControlledEnvironmentLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,                   N'Other',                   N'Other', N'O', N'O', 6, '1/1/1900', NULL, 0, 0 )

GO
