
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiNonResponseLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiNonResponseLkp] ( [DensAsiNonResponseLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,          N'Not Applicable',               N'Not Applicable', N'NotApplicable', N'N', 0, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiNonResponseLkp] ( [DensAsiNonResponseLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,            N'Not Answered',                 N'Not Answered',   N'NotAnswered', N'X', 0, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiNonResponseLkp] ( [DensAsiNonResponseLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,             N'Indifferent',                  N'Indifferent',   N'Indifferent', N'I', 0, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiNonResponseLkp] ( [DensAsiNonResponseLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Uncertain\I don''t know', N'Uncertain or "I don''t know"',     N'Uncertain', N'U', 0, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiNonResponseLkp] ( [DensAsiNonResponseLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,               N'Never Had',                    N'Never Had',      N'NeverHad', N'N', 0, '1/1/1900',       NULL, 0, 0 )

GO
