
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiInterviewerRatingLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  1, current_timestamp, 1, current_timestamp, 1, 0,             N'No real problem, treatment not needed (Low)',             N'No real problem, treatment not needed (Low)', N'0', N'0',  1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  2, current_timestamp, 1, current_timestamp, 1, 0,            N'No real problem, treatment not needed (High)',            N'No real problem, treatment not needed (High)', N'1', N'1',  2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  3, current_timestamp, 1, current_timestamp, 1, 0,  N'Slight problem, treatment probably not indicated (Low)',  N'Slight problem, treatment probably not indicated (Low)', N'2', N'2',  3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  4, current_timestamp, 1, current_timestamp, 1, 0, N'Slight problem, treatment probably not indicated (High)', N'Slight problem, treatment probably not indicated (High)', N'3', N'3',  4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  5, current_timestamp, 1, current_timestamp, 1, 0,        N'Moderate problem, some treatment indicated (Low)',        N'Moderate problem, some treatment indicated (Low)', N'4', N'4',  5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  6, current_timestamp, 1, current_timestamp, 1, 0,       N'Moderate problem, some treatment indicated (High)',       N'Moderate problem, some treatment indicated (High)', N'5', N'5',  6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  7, current_timestamp, 1, current_timestamp, 1, 0,         N'Considerable problem, treatment necessary (Low)',         N'Considerable problem, treatment necessary (Low)', N'6', N'6',  7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  8, current_timestamp, 1, current_timestamp, 1, 0,        N'Considerable problem, treatment necessary (High)',        N'Considerable problem, treatment necessary (High)', N'7', N'7',  8, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  9, current_timestamp, 1, current_timestamp, 1, 0,   N'Extreme problem, treatment absolutely necessary (Low)',   N'Extreme problem, treatment absolutely necessary (Low)', N'8', N'8',  9, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiInterviewerRatingLkp] ( [DensAsiInterviewerRatingLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 0,  N'Extreme problem, treatment absolutely necessary (High)',  N'Extreme problem, treatment absolutely necessary (High)', N'9', N'9', 10, '1/1/1900', NULL, 0, 0 )

GO
