
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiMaritalStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,                N'Married',                N'Married',            N'Married', N'M', 1, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,              N'Remarried',              N'Remarried',          N'Remarried', N'R', 2, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,                N'Widowed',                N'Widowed',            N'Widowed', N'W', 3, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,              N'Separated',              N'Separated',          N'Separated', N'L', 4, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,               N'Divorced',               N'Divorced',           N'Divorced', N'D', 5, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'Never Married - Single', N'Never Married - Single', N'NeverMarriedSingle', N'S', 6, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiMaritalStatusLkp] ( [DensAsiMaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0,           N'Cohabitating',           N'Cohabitating',       N'Cohabitating', N'C', 7, '1/1/1900',       NULL, 0, 0 )

GO
