
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiOccupationTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,       N'Major Professional/Executive',       N'Major Professional/Executive', N'EO', N'EO', 1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,   N'Manager/Nurse/Pharmacist/Teacher',   N'Manager/Nurse/Pharmacist/Teacher', N'SP', N'SP', 2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Administrator/Small Business Owner', N'Administrator/Small Business Owner', N'SB', N'SB', 3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,         N'Clerical/Sales/Technicians',         N'Clerical/Sales/Technicians', N'CS', N'CS', 4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,         N'Skilled Manual/Electrician',         N'Skilled Manual/Electrician', N'SM', N'SM', 5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,    N'Semi-Skilled/Aide/Driver/Waiter',    N'Semi-Skilled/Aide/Driver/Waiter', N'SS', N'SS', 6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0,    N'Unskilled (includes unemployed)',    N'Unskilled (includes unemployed)', N'US', N'US', 7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0,                          N'Homemaker',                          N'Homemaker', N'HM', N'HM', 8, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiOccupationTypeLkp] ( [DensAsiOccupationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9, current_timestamp, 1, current_timestamp, 1, 0,    N'Students/No Occupation/Disabled',    N'Students/No Occupation/Disabled', N'ST', N'ST', 9, '1/1/1900', NULL, 0, 0 )

GO
