
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiProblematicSubstanceLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  1, current_timestamp, 1, current_timestamp, 1, 0,     N'Alcohol and one or more drugs',     N'Alcohol and one or more drugs', N'AOMD', N'AOMD',  1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  2, current_timestamp, 1, current_timestamp, 1, 0, N'More than one drug but no alcohol', N'More than one drug but no alcohol', N'MTOD', N'MTOD',  2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  3, current_timestamp, 1, current_timestamp, 1, 0,          N'Alcohol (Any Use at All)',          N'Alcohol (Any Use at All)', N'AANY', N'AANY',  3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  4, current_timestamp, 1, current_timestamp, 1, 0,         N'Alcohol (To Intoxication)',         N'Alcohol (To Intoxication)', N'ATOX', N'ATOX',  4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  5, current_timestamp, 1, current_timestamp, 1, 0,                            N'Heroin',                            N'Heroin',  N'HRN',  N'HRN',  5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  6, current_timestamp, 1, current_timestamp, 1, 0,                         N'Methadone',                         N'Methadone',  N'MTH',  N'MTH',  6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  7, current_timestamp, 1, current_timestamp, 1, 0,          N'Other Opiates/Analgesics',          N'Other Opiates/Analgesics',  N'OOA',  N'OOA',  7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  8, current_timestamp, 1, current_timestamp, 1, 0,                      N'Barbiturates',                      N'Barbiturates',  N'BAR',  N'BAR',  8, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  9, current_timestamp, 1, current_timestamp, 1, 0, N'Sedatives/Hypnotics/Tranquilizers', N'Sedatives/Hypnotics/Tranquilizers',  N'SHT',  N'SHT',  9, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 0,                           N'Cocaine',                           N'Cocaine',  N'CCN',  N'CCN', 10, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 0,                      N'Amphetamines',                      N'Amphetamines',  N'AMP',  N'AMP', 11, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 0,                          N'Cannabis',                          N'Cannabis',  N'CAN',  N'CAN', 12, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 0,                     N'Hallucinogens',                     N'Hallucinogens',  N'HAL',  N'HAL', 13, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 14, current_timestamp, 1, current_timestamp, 1, 0,                         N'Inhalants',                         N'Inhalants',  N'INH',  N'INH', 14, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiProblematicSubstanceLkp] ( [DensAsiProblematicSubstanceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 15, current_timestamp, 1, current_timestamp, 1, 0,                        N'No Problem',                        N'No Problem',  N'NPR',  N'NPR', 15, '1/1/1900', NULL, 0, 0 )

GO
