
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiLivingArrangementTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'With Sexual Partner and Children', N'With Sexual Partner and Children', N'PC', N'PC', 1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,         N'With Sexual Partner Only',         N'With Sexual Partner Only', N'PO', N'PO', 2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,                    N'With Children',                    N'With Children', N'CH', N'CH', 3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,                     N'With Parents',                     N'With Parents', N'PR', N'PR', 4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,                      N'With Family',                      N'With Family', N'FM', N'FM', 5, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,                     N'With Friends',                     N'With Friends', N'FR', N'FR', 6, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0,                            N'Alone',                            N'Alone', N'AL', N'AL', 7, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0,           N'Controlled Environment',           N'Controlled Environment', N'CE', N'CE', 8, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiLivingArrangementTypeLkp] ( [DensAsiLivingArrangementTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9, current_timestamp, 1, current_timestamp, 1, 0,            N'No Stable Arrangement',            N'No Stable Arrangement', N'NS', N'NS', 9, '1/1/1900', NULL, 0, 0 )

GO
