
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiDrugAlcoholAdministrationRouteLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiDrugAlcoholAdministrationRouteLkp] ( [DensAsiDrugAlcoholAdministrationRouteLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,             N'Oral',             N'Oral', N'OR', N'OR', 1, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiDrugAlcoholAdministrationRouteLkp] ( [DensAsiDrugAlcoholAdministrationRouteLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,            N'Nasal',            N'Nasal', N'NS', N'NS', 2, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiDrugAlcoholAdministrationRouteLkp] ( [DensAsiDrugAlcoholAdministrationRouteLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,          N'Smoking',          N'Smoking', N'SM', N'SM', 3, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiDrugAlcoholAdministrationRouteLkp] ( [DensAsiDrugAlcoholAdministrationRouteLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Non IV Injection', N'Non IV Injection', N'NJ', N'NJ', 4, '1/1/1900', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiDrugAlcoholAdministrationRouteLkp] ( [DensAsiDrugAlcoholAdministrationRouteLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,     N'IV Injection',     N'IV Injection', N'IJ', N'IJ', 5, '1/1/1900', NULL, 0, 0 )

GO
