
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiTreatmentModalityLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,                   N'Detox (Hospital Inpatient)',                   N'Detox (Hospital Inpatient)', N'DI', N'DI', 1, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,            N'Detox (Non- Hospital Residential)',            N'Detox (Non- Hospital Residential)', N'DR', N'DR', 2, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,                           N'Detox (Outpatient)',                           N'Detox (Outpatient)', N'DO', N'DO', 3, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,               N'Treatment (Hospital Inpatient)',               N'Treatment (Hospital Inpatient)', N'TI', N'TI', 4, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,        N'Treatment (Non- Hospital Residential)',        N'Treatment (Non- Hospital Residential)', N'TR', N'TR', 5, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,                       N'Treatment (Outpatient)',                       N'Treatment (Outpatient)', N'TO', N'TO', 6, '8/19/2011', NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiTreatmentModalityLkp] ( [DensAsiTreatmentModalityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0, N'Treatment (Outpatient Methadone Maintenance)', N'Treatment (Outpatient Methadone Maintenance)', N'TM', N'TM', 7, '8/19/2011', NULL, 0, 0 )

GO
