
print '------------------------------------------------------------------------------------------'
print 'DensAsiModule_DensAsiReligionLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'Protestant', N'Protestant', N'Protestant', N'P', 1, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,   N'Catholic',   N'Catholic',   N'Catholic', N'C', 2, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,     N'Jewish',     N'Jewish',     N'Jewish', N'J', 3, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,    N'Islamic',    N'Islamic',    N'Islamic', N'I', 4, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,      N'Other',      N'Other',      N'Other', N'O', 5, '1/1/1900',       NULL, 0, 0 )
INSERT INTO [DensAsiModule].[DensAsiReligionLkp] ( [DensAsiReligionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,       N'None',       N'None',       N'None', N'N', 6, '1/1/1900',       NULL, 0, 0 )

GO
