
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraDischargeTerminationReasonLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  1, current_timestamp, 1, current_timestamp, 1, 1,                             N'01 = Left on own against staff advice with satisfactory progress',                              N'01 = Left on own against staff advice with satisfactory progress',          N'LeftSatisfactoryProgress', NULL,  1, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  2, current_timestamp, 1, current_timestamp, 1, 1,                           N'02 = Left on own against staff advice without satisfactory progres',                            N'02 = Left on own against staff advice without satisfactory progres',   N'LeftWithoutSatisfactoryProgress', NULL,  2, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  3, current_timestamp, 1, current_timestamp, 1, 1,                                        N' 03 = Involuntarily discharged due to nonparticipatio',                                         N' 03 = Involuntarily discharged due to nonparticipatio',     N'InvoluntarilyNonParticipation', NULL,  3, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  4, current_timestamp, 1, current_timestamp, 1, 1,                                     N' 04 = Involuntarily discharged due to violation of rules',                                      N' 04 = Involuntarily discharged due to violation of rules',        N'InvoluntarilyRuleViolation', NULL,  4, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  5, current_timestamp, 1, current_timestamp, 1, 1,                N'05 = Referred to another program or other services with satisfactory progress',                 N'05 = Referred to another program or other services with satisfactory progress',              N'ReferredSatisfactory', NULL,  5, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  6, current_timestamp, 1, current_timestamp, 1, 1,              N'06 = Referred to another program or other services with unsatisfactory progress',              N' 06 = Referred to another program or other services with unsatisfactory progress',            N'ReferredUnSatisfactory', NULL,  6, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  7, current_timestamp, 1, current_timestamp, 1, 1,     N'07 = Incarcerated due to offense committed while in treatment/recovery with satisfactory',      N'07 = Incarcerated due to offense committed while in treatment/recovery with satisfactory',          N'IncarceratedSatisfactory', NULL,  7, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  8, current_timestamp, 1, current_timestamp, 1, 1,   N'08 = Incarcerated due to offense committed while in treatment/recovery with unsatisfactory',   N'08 = Incarcerated due to offense committed while in treatment/recovery with unsatisfactory ',        N'IncarceratedUnSatisfactory', NULL,  8, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  9, current_timestamp, 1, current_timestamp, 1, 1, N'09 = Incarcerated due to old warrant or charged from before entering treatment/recovery with', N'09 = Incarcerated due to old warrant or charged from before entering treatment/recovery with ',   N'IncarceratedWarrantSatisfactory', NULL,  9, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 1, N'10 = Incarcerated due to old warrant or charged from before entering treatment/recovery with', N'10 = Incarcerated due to old warrant or charged from before entering treatment/recovery with ', N'IncarceratedWarrantUnSatisfactory', NULL, 10, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 1,                                      N'11 = Transferred to another facility for health reasons',                                      N'11 = Transferred to another facility for health reasons ',                    N'TransferHealth', NULL, 11, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 1,                                                                                  N' 12 = Death',                                                                                   N' 12 = Death',                             N'Death', NULL, 12, '8/31/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraDischargeTerminationReasonLkp] ( [GpraDischargeTerminationReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 1,                                                                        N' 13 = Other (Specify)',                                                                         N' 13 = Other (Specify)',                             N'Other', NULL, 13, '8/31/2011',       NULL, 1, 0 )

GO
