
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraFollowUpStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 1,                     N'01 = Deceased at time of due date',                     N'01 = Deceased at time of due date',                     N'Deceased', NULL, 1, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 1,      N'11 = Completed interview within specified window',      N'11 = Completed interview within specified window',              N'CompletedWithin', NULL, 2, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 1,     N'12 = Completed interview outside specified window',     N'12 = Completed interview outside specified window',             N'CompletedOutside', NULL, 3, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 1,                N'21 = Located, but refused, unspecified',                N'21 = Located, but refused, unspecified',               N'LocatedRefused', NULL, 4, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 1, N'22 = Located, but unable to gain institutional access', N'22 = Located, but unable to gain institutional access', N'LocatedNoInstitutionalAccess', NULL, 5, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 1,     N'23 = Located, but otherwise unable to gain access',     N'23 = Located, but otherwise unable to gain access',              N'LocatedNoAccess', NULL, 6, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 1,              N'24 = Located, but withdrawn from project',              N'24 = Located, but withdrawn from project',             N'LocatedWithdrawn', NULL, 7, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 1,                          N'31 = Unable to locate, moved',                          N'31 = Unable to locate, moved',                        N'Moved', NULL, 8, '8/20/2011',       NULL, 1, 0 )
INSERT INTO [GpraModule].[GpraFollowUpStatusLkp] ( [GpraFollowUpStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9, current_timestamp, 1, current_timestamp, 1, 1,                N'32 = Unable to locate, other (SPECIFY)',                N'32 = Unable to locate, other (SPECIFY)',                        N'Other', NULL, 9, '8/20/2011',       NULL, 1, 0 )

GO
