
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraOverallHealthLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraOverallHealthLkp] ( [GpraOverallHealthLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 1, N'Excellent', N'Excellent', NULL, NULL, 1, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraOverallHealthLkp] ( [GpraOverallHealthLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 1, N'Very good', N'Very good', NULL, NULL, 2, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraOverallHealthLkp] ( [GpraOverallHealthLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 1,      N'Good',      N'Good', NULL, NULL, 3, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraOverallHealthLkp] ( [GpraOverallHealthLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 1,      N'Fair',      N'Fair', NULL, NULL, 4, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraOverallHealthLkp] ( [GpraOverallHealthLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 1,      N'Poor',      N'Poor', NULL, NULL, 5, '3/31/2011',       NULL, 0, 0 )

GO
