
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraPsychologicalImpactLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraPsychologicalImpactLkp] ( [GpraPsychologicalImpactLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 1,   N'Not at all',   N'Not at all',     N'NotAtAll', NULL, 1, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraPsychologicalImpactLkp] ( [GpraPsychologicalImpactLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 1,     N'Slightly',     N'Slightly',     N'Slightly', NULL, 2, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraPsychologicalImpactLkp] ( [GpraPsychologicalImpactLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 1,   N'Moderately',   N'Moderately',   N'Moderately', NULL, 3, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraPsychologicalImpactLkp] ( [GpraPsychologicalImpactLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 1, N'Considerably', N'Considerably', N'Considerably', NULL, 4, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraPsychologicalImpactLkp] ( [GpraPsychologicalImpactLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 1,    N'Extremely',    N'Extremely',    N'Extremely', NULL, 5, '3/31/2011',       NULL, 0, 0 )

GO
