
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraEducationLevelLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  1, current_timestamp, 1, current_timestamp, 1, 1,                                                 N'Never attended school',                                                 N'Never attended school', NULL, NULL,  1, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  2, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'1st grade completed',                                                   N'1st grade completed', NULL, NULL,  2, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  3, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'2nd grade completed',                                                   N'2nd grade completed', NULL, NULL,  3, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  4, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'3rd grade completed',                                                   N'3rd grade completed', NULL, NULL,  4, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  5, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'4th grade completed',                                                   N'4th grade completed', NULL, NULL,  5, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  6, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'5th grade completed',                                                   N'5th grade completed', NULL, NULL,  6, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  7, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'6th grade completed',                                                   N'6th grade completed', NULL, NULL,  7, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  8, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'7th grade completed',                                                   N'7th grade completed', NULL, NULL,  8, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  9, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'8th grade completed',                                                   N'8th grade completed', NULL, NULL,  9, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 1,                                                   N'9th grade completed',                                                   N'9th grade completed', NULL, NULL, 10, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 1,                                                  N'10th grade completed',                                                  N'10th grade completed', NULL, NULL, 11, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 1,                                                  N'11th Grade Completed',                                                  N'11th Grade Completed', NULL, NULL, 12, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 1,                   N'12th grade completed/high school diploma/equivalent',                   N'12th grade completed/high school diploma/equivalent', NULL, NULL, 13, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 14, current_timestamp, 1, current_timestamp, 1, 1,                              N'College or university/1st year completed',                              N'College or university/1st year completed', NULL, NULL, 14, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 15, current_timestamp, 1, current_timestamp, 1, 1, N'College or university/2nd year completed/Associate''s degree (AA, AS)', N'College or university/2nd year completed/Associate''s degree (AA, AS)', NULL, NULL, 15, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 16, current_timestamp, 1, current_timestamp, 1, 1,                                   N'College or university/3rd completed',                                   N'College or university/3rd completed', NULL, NULL, 16, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 17, current_timestamp, 1, current_timestamp, 1, 1,                                 N'Bachelor''s degree (BA, BS) or higher',                                 N'Bachelor''s degree (BA, BS) or higher', NULL, NULL, 17, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 18, current_timestamp, 1, current_timestamp, 1, 1,            N'Voc/tech program after high school but no voc/tech diploma',            N'Voc/tech program after high school but no voc/tech diploma', NULL, NULL, 18, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEducationLevelLkp] ( [GpraEducationLevelLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 19, current_timestamp, 1, current_timestamp, 1, 1,                                    N'Voc/tech diploma after high school',                                    N'Voc/tech diploma after high school', NULL, NULL, 19, '3/31/2011',       NULL, 0, 0 )

GO
