
print '------------------------------------------------------------------------------------------'
print 'GpraModule_GpraEmploymentStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 1,                            N'Other',                            N'Other', NULL, NULL, 8, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 1,               N'Employed full time',               N'Employed full time', NULL, NULL, 1, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 1,               N'Employed part time',               N'Employed part time', NULL, NULL, 2, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 1,     N'Unemployed, looking for work',     N'Unemployed, looking for work', NULL, NULL, 3, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 1,             N'Unemployed, disabled',             N'Unemployed, disabled', NULL, NULL, 4, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 1,       N'Unemployed, volunteer work',       N'Unemployed, volunteer work', NULL, NULL, 5, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 1,              N'Unemployed, retired',              N'Unemployed, retired', NULL, NULL, 6, '3/31/2011',       NULL, 0, 0 )
INSERT INTO [GpraModule].[GpraEmploymentStatusLkp] ( [GpraEmploymentStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 1, N'Unemployed, not looking for work', N'Unemployed, not looking for work', NULL, NULL, 7, '3/31/2011',       NULL, 0, 0 )

GO
