
print '------------------------------------------------------------------------------------------'
print 'ImmunizationModule_ImmunizationUnitOfMeasureLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,     N'%',         N'Percent',         N'Percent',     N'%', NULL, '7/6/2011',  '7/6/2011', 0, 0,     N'%' )
INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,   N'meq', N'MilliEquivalent', N'MilliEquivalent',   N'meq', NULL, '7/6/2011',  '7/6/2011', 0, 0,   N'meq' )
INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,    N'mg',       N'MilliGram',       N'MilliGram',    N'mg', NULL, '7/6/2011',  '7/6/2011', 0, 0,    N'mg' )
INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,    N'mL',      N'MilliLiter',      N'MilliLiter',    N'mL', NULL, '7/6/2011',  '7/6/2011', 0, 0,    N'mL' )
INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Cells',           N'Cells',           N'Cells', N'Cells', NULL, '7/6/2011',  '7/6/2011', 0, 0, N'Cells' )
INSERT INTO [ImmunizationModule].[ImmunizationUnitOfMeasureLkp] ( [ImmunizationUnitOfMeasureLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,   N'UNT',            N'Unit',            N'Unit',   N'UNT', NULL, '7/6/2011',  '7/6/2011', 0, 0,   N'UNT' )

GO
