print '------------------------------------------------------------------------------------------'
print 'LabModule_LabTestNameLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 1,    N'Complete Blood Count w/ Differential (CBC)', N'Complete Blood Count w/ Differential (CBC)', N'CBC', N'CBC', 1, '1/1/2000',  '1/1/2020', 1, 0, N'9564003' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 1,    N'BUN',    N'Blood Urea Nitrogen', N'BUN', N'BUN', 1, '1/1/2000',  '1/1/2020', 1, 0, N'105011006' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 1,    N'Triglycerides',    N'Triglycerides',  N'TGL',  N'TGL', 1, '1/1/2000',  '1/1/2020', 1, 0,  N'14740000' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 1,    N'Fasting Blood Glucose',    N'Fasting Blood Glucose',  N'FBG',  N'FBG', 1, '1/1/2000',  '1/1/2020', 1, 0,  N'271062006' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 1,    N'Thyroid Stimulating Hormone (TSH)',    N'Thyroid Stimulating Hormone (TSH)',  N'TSH',  N'TSH', 1, '1/1/2000',  '1/1/2020', 1, 0,  N'61167004' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 1,    N'High-sensitivity C-reactive protein (HS-CRP)',    N'High-sensitivity C-reactive protein (HS-CRP)',  N'HSCRP',  N'HSCRP', 1, '1/1/2000',  '1/1/2020', 1, 0,  N'55235003' )
INSERT INTO [LabModule].[LabTestNameLkp] ( [LabTestNameLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 1,    N'Imported Lab Test',    N'Imported Lab Test',  N'ImportedTest',  N'ImportedTest', 1, '1/1/2000',  '1/1/2020', 1, 0,  N'99999999' )


GO