
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PayorSubscriberRelationshipCacheTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,             N'Spouse', NULL,            N'Spouse', N'01', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,               N'Self', NULL,              N'Self', N'18', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0,              N'Child', NULL,             N'Child', N'19', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,           N'Employee', NULL,          N'Employee', N'20', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,        N'Organ Donor', NULL,        N'OrganDonor', N'39', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0,      N'Cadaver Donor', NULL,      N'CadaverDonor', N'40', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0,       N'Life Partner', NULL,       N'LifePartner', N'53', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PayorSubscriberRelationshipCacheTypeLkp] ([PayorSubscriberRelationshipCacheTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0, N'Other Relationship', NULL, N'OtherRelationship', N'G8', 0, '1/1/1900',        NULL, 0, 0 )

GO

