
print '------------------------------------------------------------------------------------------'
print 'PatientModule_SmokingStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100000, current_timestamp, 1, current_timestamp, 1, 0,       N'Current every day smoker', NULL,                 N'EverydaySmoker', N'DSK', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100001, current_timestamp, 1, current_timestamp, 1, 0,        N'Current some day smoker', NULL,                  N'SomedaySmoker', N'SSK', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100002, current_timestamp, 1, current_timestamp, 1, 0,                  N'Former smoker', NULL,                   N'FormerSmoker', N'FSK', 3, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100003, current_timestamp, 1, current_timestamp, 1, 0,                   N'Never smoker', NULL,                    N'NeverSmoker', N'NSK', 4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100005, current_timestamp, 1, current_timestamp, 1, 0, N'Smoker, current status unknown', NULL, N'Smoker, current status unknown', N'CSU', 6, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SmokingStatusLkp] ( [SmokingStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1100006, current_timestamp, 1, current_timestamp, 1, 0,         N'Unknown if ever smoked', NULL,         N'Unknown if ever smoked', N'USK', 7, '1/1/1900',        NULL, 0, 0 )

GO
