
print '------------------------------------------------------------------------------------------'
print 'PatientModule_SpecialNeedLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1467242, current_timestamp, 1, current_timestamp, 1, 0,                         N'Ambulation – Uses a walker', NULL,  N'AUW',  N'AUW', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1593882, current_timestamp, 1, current_timestamp, 1, 0,                   N'Ambulation – Cannot climb stairs', NULL, N'ACCS', N'ACCS', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2214689, current_timestamp, 1, current_timestamp, 1, 0,              N'Ambulation – Confined to a wheelchair', NULL,  N'ACW',  N'ACW', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2784324, current_timestamp, 1, current_timestamp, 1, 0,                               N'Dietary – Vegetarian', NULL,   N'DV',   N'DV', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3381769, current_timestamp, 1, current_timestamp, 1, 0,                                   N'Dietary – Kosher', NULL,   N'DK',   N'DK', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3390314, current_timestamp, 1, current_timestamp, 1, 0,                                  N'Dietary – Cardiac', NULL,   N'DC',   N'DC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4185331, current_timestamp, 1, current_timestamp, 1, 0,                              N'Hearing – Slight loss', NULL,  N'HSL',  N'HSL', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5975287, current_timestamp, 1, current_timestamp, 1, 0,                  N'Hearing – Moderate to Severe Loss', NULL, N'HMSL', N'HMSL', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7426405, current_timestamp, 1, current_timestamp, 1, 0,                                   N'Other - Pregnant', NULL,   N'OP',   N'OP', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7857404, current_timestamp, 1, current_timestamp, 1, 0, N'Other – Requires assistance to enter/exit building', NULL,  N'ORA',  N'ORA', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[SpecialNeedLkp] ( [SpecialNeedLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8569547, current_timestamp, 1, current_timestamp, 1, 0,                             N'Other – Shuttle Pickup', NULL,  N'OSP',  N'OSP', 0, '1/1/1900',        NULL, 0, 0 )

GO
