
print '------------------------------------------------------------------------------------------'
print 'PatientModule_RaceLkp'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (233746,  current_timestamp, 1, current_timestamp, 1, 0, N'Alaska Native',                              NULL, N'AlaskaNative',                          N'ALN', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (4663764, current_timestamp, 1, current_timestamp, 1, 0, N'American Indian',                            NULL, N'AmericanIndian',                        N'AMI', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (5252654, current_timestamp, 1, current_timestamp, 1, 0, N'Asian',                                      NULL, N'Asian',                                 N'ASN', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (5544877, current_timestamp, 1, current_timestamp, 1, 0, N'Black or African American',                  NULL, N'BlackorAfricanAmerican',                N'BAA', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (7794176, current_timestamp, 1, current_timestamp, 1, 0, N'Native Hawaiian and Other Pacific Islander', NULL, N'NativeHawaiianandOtherPacificIslander', N'NHO', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (9056023, current_timestamp, 1, current_timestamp, 1, 0, N'White',                                      NULL, N'White',                                 N'WHT', '19000101', NULL, 0,    0, 0)
INSERT INTO [PatientModule].[RaceLkp] ([RaceLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [EffectiveStartDate], [EffectiveEndDate], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator]) VALUES (9056024, current_timestamp, 1, current_timestamp, 1, 0, N'Other',                                      NULL, N'Other',                                 N'OTH', '19000101', NULL, 1000, 0, 0)


GO

