
print '------------------------------------------------------------------------------------------'
print 'PatientModule_RaceDetailedEthnicity'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (417028,  current_timestamp, 1, current_timestamp, 1, 0, 233746, 5362565)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (2204624, current_timestamp, 1, current_timestamp, 1, 0, 233746, 5973793)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (2496555, current_timestamp, 1, current_timestamp, 1, 0, 233746, 7565474)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (2523110, current_timestamp, 1, current_timestamp, 1, 0, 233746, 4259761)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (2783188, current_timestamp, 1, current_timestamp, 1, 0, 233746, 2800470)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (3110844, current_timestamp, 1, current_timestamp, 1, 0, 233746, 646821)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (3272519, current_timestamp, 1, current_timestamp, 1, 0, 233746, 5313743)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (3523024, current_timestamp, 1, current_timestamp, 1, 0, 233746, 2217706)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (6130516, current_timestamp, 1, current_timestamp, 1, 0, 233746, 1174037)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (6242770, current_timestamp, 1, current_timestamp, 1, 0, 233746, 3958444)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (6445714, current_timestamp, 1, current_timestamp, 1, 0, 233746, 9255473)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (6721226, current_timestamp, 1, current_timestamp, 1, 0, 233746, 6028489)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (6721227, current_timestamp, 1, current_timestamp, 1, 0, 233746, 6898322)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7072273, current_timestamp, 1, current_timestamp, 1, 0, 233746, 148481)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7072274, current_timestamp, 1, current_timestamp, 1, 0, 233746, 8335128)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7730448, current_timestamp, 1, current_timestamp, 1, 0, 233746, 6061948)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7730449, current_timestamp, 1, current_timestamp, 1, 0, 233746, 5335511)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7851261, current_timestamp, 1, current_timestamp, 1, 0, 233746, 892261)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (7851262, current_timestamp, 1, current_timestamp, 1, 0, 233746, 892261)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (9220550, current_timestamp, 1, current_timestamp, 1, 0, 233746, 5163408)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (9220551, current_timestamp, 1, current_timestamp, 1, 0, 7794176, 8493496)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (9220552, current_timestamp, 1, current_timestamp, 1, 0, 7794176, 5428938)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (9220553, current_timestamp, 1, current_timestamp, 1, 0, 7794176, 420433)
INSERT INTO [PatientModule].[RaceDetailedEthnicity] ([RaceDetailedEthnicityKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [RaceLkpKey], [DetailedEthnicityLkpKey]) VALUES (9220554, current_timestamp, 1, current_timestamp, 1, 0, 7794176, 8493496)


GO

