
print '------------------------------------------------------------------------------------------'
print 'PatientModule_MedicationDoseUnitLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2737282, current_timestamp, 1, current_timestamp, 1, 0, N'Cells', NULL, N'CELLS', N'CELLS', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6611603, current_timestamp, 1, current_timestamp, 1, 0,    N'Milliequivalent', NULL, N'MEQ', N'MEQ', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7222147, current_timestamp, 1, current_timestamp, 1, 0,  N'Milligram', NULL, N'MG ', N'MG ', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8426025, current_timestamp, 1, current_timestamp, 1, 0, N'Milliliter', NULL, N'ML ', N'ML ', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8908465, current_timestamp, 1, current_timestamp, 1, 0,   N'Unit', NULL, N'UNT', N'UNT', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MedicationDoseUnitLkp] ( [MedicationDoseUnitLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8908466, current_timestamp, 1, current_timestamp, 1, 0,   N'Percentage', NULL, N'%', N'%', NULL, '12/18/2008',        NULL, 0, 0 )

GO
