
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientDocumentTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientDocumentTypeLkp] ( [PatientDocumentTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10000, current_timestamp, 1, current_timestamp, 1, 0, N'Patient Demographics', NULL,    N'PD',    N'PD', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientDocumentTypeLkp] ( [PatientDocumentTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10001, current_timestamp, 1, current_timestamp, 1, 0,          N'Lab Results', NULL,    N'LR',    N'LR', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientDocumentTypeLkp] ( [PatientDocumentTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10002, current_timestamp, 1, current_timestamp, 1, 0,                  N'C32', NULL,   N'C32',   N'C32', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientDocumentTypeLkp] ( [PatientDocumentTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10003, current_timestamp, 1, current_timestamp, 1, 0,                  N'XDM', NULL,   N'XDM',   N'XDM', 3, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientDocumentTypeLkp] ( [PatientDocumentTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10004, current_timestamp, 1, current_timestamp, 1, 0,                N'Other', NULL, N'Other', N'Other', 4, '1/1/1900',        NULL, 0, 0 )

GO
