
print '------------------------------------------------------------------------------------------'
print 'PatientModule_VeteranServiceBranchLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[VeteranServiceBranchLkp] ( [VeteranServiceBranchLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,         N'Army', NULL,  N'Army',  N'Army', 2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranServiceBranchLkp] ( [VeteranServiceBranchLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,    N'Air Force', NULL,    N'AF',    N'AF', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranServiceBranchLkp] ( [VeteranServiceBranchLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Marine Corps', NULL,    N'MC',    N'MC', 4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranServiceBranchLkp] ( [VeteranServiceBranchLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,         N'Navy', NULL,  N'Navy',  N'Navy', 5, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranServiceBranchLkp] ( [VeteranServiceBranchLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,  N'Coast Guard', NULL,   N'CG',     N'CG', 3, '1/1/1900',        NULL, 0, 0 )
GO
