
print '------------------------------------------------------------------------------------------'
print 'PatientModule_VeteranDischargeStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[VeteranDischargeStatusLkp] ( [VeteranDischargeStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0,            N'Honorable', NULL,  N'Honorable',  N'Honorable', 4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranDischargeStatusLkp] ( [VeteranDischargeStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0,              N'General', NULL,    N'General',    N'General', 3, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranDischargeStatusLkp] ( [VeteranDischargeStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Other than Honorable', NULL,        N'NTH',        N'NTH', 5, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranDischargeStatusLkp] ( [VeteranDischargeStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0,          N'Bad Conduct', NULL,         N'BC',         N'BC', 1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[VeteranDischargeStatusLkp] ( [VeteranDischargeStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0,         N'Dishonorable', NULL,         N'DH',         N'DH', 2, '1/1/1900',        NULL, 0, 0 )
GO
