
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientGenderLkpKey.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 352156,  0,  N'FM', N'Female Becoming Male ',   N'FM', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 1, 1, 1,'1/1/1900', NULL )
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 2173041, 0,   N'F',               N'Female ',    N'F', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 2, 1, 1,'1/1/1900', NULL )
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 2173042, 0,  N'MF', N'Male Becoming Female ',   N'MF', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 2, 1, 1,'1/1/1900', NULL )        
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 2173043, 0, N'MFF', N'Male Formerly Female ',  N'MFF', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 1, 1, 1,'1/1/1900', NULL )
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 6337882, 0, N'FFM', N'Female Formerly Male ',  N'FMM', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 2, 1, 1,'1/1/1900', NULL )         
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 6,       0, N'UND',      N'Undifferentiated',  N'UND', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 3, 1, 1,'1/1/1900', NULL )
INSERT INTO [PatientModule].[PatientGenderLkp]( [PatientGenderLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [AdministrativeGenderLkpKey], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate] ) VALUES ( 6337881, 0,   N'M',                  N'Male',    N'M', NULL, 1000, 0, 0, current_timestamp, current_timestamp, 1, 1, 1,'1/1/1900', NULL )

