
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientIdentifierTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295601, current_timestamp, 1, current_timestamp, 1, 0,        N'Social Security #', NULL, N'SSN', N'SSN',    0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295602, current_timestamp, 1, current_timestamp, 1, 0,      N'Driver''S License #', NULL, N'DRV', N'DRV',    0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295603, current_timestamp, 1, current_timestamp, 1, 0,             N'Court Case #', NULL, N'CCN', N'CCN',    0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295604, current_timestamp, 1, current_timestamp, 1, 0,               N'State ID #', NULL, N'SID', N'SID',    0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295605, current_timestamp, 1, current_timestamp, 1, 0, N'Medical Record/Account #', NULL, N'ACT', N'ACT',    0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientIdentifierTypeLkp] ( [PatientIdentifierTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1295606, current_timestamp, 1, current_timestamp, 1, 0,                 N'Other ID', NULL, N'OTH', N'OTH', 1000, '1/1/1900',        NULL, 0, 0 )

GO
