
print '------------------------------------------------------------------------------------------'
print 'PatientModule_CustodialStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1376599, current_timestamp, 1, current_timestamp, 1, 0, N'Adoptive Parents / Legal Guardian', NULL, N'AP', N'AP', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1537743, current_timestamp, 1, current_timestamp, 1, 0,                       N'OCS Custody', NULL, N'OC', N'OC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1737647, current_timestamp, 1, current_timestamp, 1, 0,               N'Tribal Organization', NULL, N'TO', N'TO', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3149167, current_timestamp, 1, current_timestamp, 1, 0,                              N'Self', NULL, N'SF', N'SF', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5706943, current_timestamp, 1, current_timestamp, 1, 0,            N'Biological Mother Only', NULL, N'BM', N'BM', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5893044, current_timestamp, 1, current_timestamp, 1, 0,                   N'Other (Specify)', NULL, N'OT', N'OT', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8950314, current_timestamp, 1, current_timestamp, 1, 0,           N'Both Biological Parents', NULL, N'BP', N'BP', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[CustodialStatusLkp] ( [CustodialStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9518027, current_timestamp, 1, current_timestamp, 1, 0,            N'Biological Father Only', NULL, N'BF', N'BF', 0, '1/1/1900',        NULL, 0, 0 )

GO
