
print '------------------------------------------------------------------------------------------'
print 'PatientModule_ReactionLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50000, current_timestamp, 1, current_timestamp, 1, 0,                     N'diarrhea', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38192' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50001, current_timestamp, 1, current_timestamp, 1, 0,                        N'hives', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38193' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50002, current_timestamp, 1, current_timestamp, 1, 0,             N'photosensitivity', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38194' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50003, current_timestamp, 1, current_timestamp, 1, 0,         N'irregular heart rate', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38195' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50004, current_timestamp, 1, current_timestamp, 1, 0,         N'respiratory distress', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38196' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50005, current_timestamp, 1, current_timestamp, 1, 0,                      N'itching', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38197' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50006, current_timestamp, 1, current_timestamp, 1, 0,                 N'swollen lips', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38198' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50007, current_timestamp, 1, current_timestamp, 1, 0,                       N'nausea', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38199' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50008, current_timestamp, 1, current_timestamp, 1, 0,                     N'vomiting', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38200' )
INSERT INTO [PatientModule].[ReactionLkp] ( [ReactionLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 50009, current_timestamp, 1, current_timestamp, 1, 0,           N'Anaphylactic Shock', NULL, NULL, NULL, NULL, '1/1/1900', NULL, 0, 0, N'C38201' )

GO
