
print '------------------------------------------------------------------------------------------'
print 'PatientModule_AllergySeverityTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 352046, current_timestamp, 1, current_timestamp, 1, 0,               N'Mild', NULL,             N'Mild', NULL, NULL, '1/1/1900',        NULL, 0, 0, N'255604002' )
INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 573947, current_timestamp, 1, current_timestamp, 1, 0,   N'Mild to moderate', NULL,   N'MildToModerate', NULL, NULL, '1/1/1900',        NULL, 0, 0, N'371923003' )
INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 583448, current_timestamp, 1, current_timestamp, 1, 0,           N'Moderate', NULL,         N'Moderate', NULL, NULL, '1/1/1900',        NULL, 0, 0,   N'6736007' )
INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 672049, current_timestamp, 1, current_timestamp, 1, 0, N'Moderate to severe', NULL, N'ModerateToSevere', NULL, NULL, '1/1/1900',        NULL, 0, 0, N'371924009' )
INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 682550, current_timestamp, 1, current_timestamp, 1, 0,             N'Severe', NULL,           N'Severe', NULL, NULL, '1/1/1900',        NULL, 0, 0,  N'24484000' )
INSERT INTO [PatientModule].[AllergySeverityTypeLkp] ( [AllergySeverityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CodedConceptCode] ) VALUES ( 920051, current_timestamp, 1, current_timestamp, 1, 0,              N'Fatal', NULL,            N'Fatal', NULL, NULL, '1/1/1900',        NULL, 0, 0, N'399166001' )

GO
