print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientContactPhoneTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientContactPhoneTypeLkp] ([PatientContactPhoneTypeLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate]) VALUES (1, 1, N'H', N'Home', N'H', N'Home phone', 0, 1, 1, current_timestamp, current_timestamp, 1, 1, '1/1/1900', NULL)
INSERT INTO [PatientModule].[PatientContactPhoneTypeLkp] ([PatientContactPhoneTypeLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate]) VALUES (2, 1, N'C', N'Cell', N'H', N'Cell phone', 1, 1, 1, current_timestamp, current_timestamp, 1, 1, '1/1/1900', NULL)
INSERT INTO [PatientModule].[PatientContactPhoneTypeLkp] ([PatientContactPhoneTypeLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate]) VALUES (3, 1, N'W', N'Work', N'H', N'Work phone', 2, 1, 1, current_timestamp, current_timestamp, 1, 1, '1/1/1900', NULL)
INSERT INTO [PatientModule].[PatientContactPhoneTypeLkp] ([PatientContactPhoneTypeLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate]) VALUES (4, 1, N'F', N'Fax', N'H', N'Fax', 3, 1, 1, current_timestamp, current_timestamp, 1, 1, '1/1/1900', NULL)
INSERT INTO [PatientModule].[PatientContactPhoneTypeLkp] ([PatientContactPhoneTypeLkpKey], [Version], [WellKnownName], [Name], [ShortName], [Description], [SortOrderNumber], [SystemOwnedIndicator], [DefaultIndicator], [CreatedTimestamp], [UpdatedTimestamp], [CreatedBySystemAccountKey], [UpdatedBySystemAccountKey], [EffectiveStartDate], [EffectiveEndDate]) VALUES (5, 1, N'O', N'Other', N'H', N'Other', 4, 1, 1, current_timestamp, current_timestamp, 1, 1, '1/1/1900', NULL)

GO