
print '------------------------------------------------------------------------------------------'
print 'PatientModule_LegalAuthorizationTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  892690, current_timestamp, 1, current_timestamp, 1, 0,                                 N'Commitment', NULL, N'CMT', N'CMT', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  999180, current_timestamp, 1, current_timestamp, 1, 0,                  N'Court order for treatment', NULL, N'COT', N'COT', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1012959, current_timestamp, 1, current_timestamp, 1, 0, N'Court order for observation and evaluation', NULL, N'COO', N'COO', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1312133, current_timestamp, 1, current_timestamp, 1, 0,                    N'Pre-trial/self referral', NULL, N'PTR', N'PTR', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1762975, current_timestamp, 1, current_timestamp, 1, 0,                               N'Incarcerated', NULL, N'INC', N'INC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1876006, current_timestamp, 1, current_timestamp, 1, 0,                           N'Probation/Parole', NULL, N'PRB', N'PRB', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2440727, current_timestamp, 1, current_timestamp, 1, 0,                        N'None/No Involvement', NULL,  N'NI',  N'NI', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3417433, current_timestamp, 1, current_timestamp, 1, 0,                                 N'Drug Court', NULL,  N'DC',  N'DC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3977779, current_timestamp, 1, current_timestamp, 1, 0,                                N'No Response', NULL,  N'NR',  N'NR', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6756694, current_timestamp, 1, current_timestamp, 1, 0,                                    N'Unknown', NULL,  N'UN',  N'UN', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6913300, current_timestamp, 1, current_timestamp, 1, 0,                          N'Deferred Sentence', NULL,  N'DS',  N'DS', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8834333, current_timestamp, 1, current_timestamp, 1, 0,                 N'Court order for evaluation', NULL, N'COE', N'COE', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[LegalAuthorizationTypeLkp] ( [LegalAuthorizationTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9141143, current_timestamp, 1, current_timestamp, 1, 0,                       N'Deferred Prosecution', NULL,  N'DP',  N'DP', 0, '1/1/1900',        NULL, 0, 0 )

GO
