
print '------------------------------------------------------------------------------------------'
print 'PatientModule_DisabilityLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES (  145674, current_timestamp, 1, current_timestamp, 1, 0,                                N'Deaf', NULL,   N'DF',   N'DF', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1213585, current_timestamp, 1, current_timestamp, 1, 0,              N'Blind (Legal/Physical)', NULL,   N'BL',   N'BL', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2662015, current_timestamp, 1, current_timestamp, 1, 0,            N'Paralysis - Quadriplegic', NULL,   N'PQ',   N'PQ', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4845205, current_timestamp, 1, current_timestamp, 1, 0,              N'Paralysis - Paraplegic', NULL,   N'PP',   N'PP', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8622684, current_timestamp, 1, current_timestamp, 1, 0,     N'Developmentally Disabled - Mild', NULL,  N'DDM',  N'DDM', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8844957, current_timestamp, 1, current_timestamp, 1, 0,   N'Developmentally Disabled - Severe', NULL,  N'DDS',  N'DDS', NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[DisabilityLkp] ( [DisabilityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9445021, current_timestamp, 1, current_timestamp, 1, 0, N'Developmentally Disabled - Moderate', NULL, N'DDMO', N'DDMO', NULL, '1/1/1900',        NULL, 0, 0 )

GO
