
print '------------------------------------------------------------------------------------------'
print 'PatientModule_MaritalStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[MaritalStatusLkp] ( [MaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2737282, current_timestamp, 1, current_timestamp, 1, 0, N'Separated', NULL, N'SP', N'SP', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MaritalStatusLkp] ( [MaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6611603, current_timestamp, 1, current_timestamp, 1, 0,    N'Single', NULL, N'SG', N'SG', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MaritalStatusLkp] ( [MaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7222147, current_timestamp, 1, current_timestamp, 1, 0,  N'Married ', NULL, N'M ', N'M ', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MaritalStatusLkp] ( [MaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8426025, current_timestamp, 1, current_timestamp, 1, 0, N'Divorced ', NULL, N'D ', N'D ', NULL, '12/18/2008',        NULL, 0, 0 )
INSERT INTO [PatientModule].[MaritalStatusLkp] ( [MaritalStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8908465, current_timestamp, 1, current_timestamp, 1, 0,   N'Widowed', NULL, N'WD', N'WD', NULL, '12/18/2008',        NULL, 0, 0 )

GO
