
print '------------------------------------------------------------------------------------------'
print 'PatientModule_ImmigrationStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1976755, current_timestamp, 1, current_timestamp, 1, 0, N'Work Visa (H-1, H2, L1, L2, B1)', NULL, N'WV', N'WV', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1976757, current_timestamp, 1, current_timestamp, 1, 0,       N'Fiance of US Citizen (K1)', NULL, N'FC', N'FC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1976759, current_timestamp, 1, current_timestamp, 1, 0,           N'Religious Worker (R1)', NULL, N'RW', N'RW', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1976785, current_timestamp, 1, current_timestamp, 1, 0,           N'Student Visa (F1, M1)', NULL, N'SV', N'SV', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3245456, current_timestamp, 1, current_timestamp, 1, 0,     N'Temporary Visitor Visa (B2)', NULL, N'TV', N'TV', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3245458, current_timestamp, 1, current_timestamp, 1, 0,       N'Spouse of US Citizen (K3)', NULL, N'SC', N'SC', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3245460, current_timestamp, 1, current_timestamp, 1, 0,           N'Exchange Visitor (J1)', NULL, N'EV', N'EV', 0, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[ImmigrationStatusLkp] ( [ImmigrationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3245487, current_timestamp, 1, current_timestamp, 1, 0, N'Permanent Resident (Green Card)', NULL, N'PR', N'PR', 0, '1/1/1900',        NULL, 0, 0 )

GO
