
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientPhoneTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientPhoneTypeLkp] ( [PatientPhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3511169, current_timestamp, 1, current_timestamp, 1, 0, N'Other', NULL, N'Other', N'OTH', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientPhoneTypeLkp] ( [PatientPhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5983855, current_timestamp, 1, current_timestamp, 1, 0,  N'Cell', NULL,  N'Cell',   N'C',    2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientPhoneTypeLkp] ( [PatientPhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6911176, current_timestamp, 1, current_timestamp, 1, 0,   N'Fax', NULL,   N'Fax',   N'F',    4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientPhoneTypeLkp] ( [PatientPhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8480151, current_timestamp, 1, current_timestamp, 1, 0,  N'Work', NULL,  N'Work',   N'O',    3, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientPhoneTypeLkp] ( [PatientPhoneTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8773881, current_timestamp, 1, current_timestamp, 1, 0,  N'Home', NULL,  N'Home',   N'H',    1, '1/1/1900',        NULL, 0, 0 )

GO
