
print '------------------------------------------------------------------------------------------'
print 'PatientModule_PatientAddressTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1456680, current_timestamp, 1, current_timestamp, 1, 0,               N'Billing',                                                                                                                                                                                                                                                                                        NULL,             N'Billing',  N'BL', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2386448, current_timestamp, 1, current_timestamp, 1, 0,                  N'Home', N'A communication address at a home, attempted contacts for business purposes might intrude privacy and chances are one will contact family or other household members instead of the person one wishes to call. Typically used with urgent cases, or if no other contacts are available. ',                N'Home',   N'H',    1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3664656, current_timestamp, 1, current_timestamp, 1, 0,           N'Work/Office',                                                                                                                                                                                                     N'An office address. First choice for business related contacts during business hours.',          N'WorkOffice',  N'WO',    2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5000221, current_timestamp, 1, current_timestamp, 1, 0,              N'Homeless',                                                                                                                                                                                                                                                                                        NULL,            N'Homeless', N'HML', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6219671, current_timestamp, 1, current_timestamp, 1, 0,               N'Mailing',                                                                                                                                                                                                                                                                                        NULL,             N'Mailing',  N'HL', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7816849, current_timestamp, 1, current_timestamp, 1, 0,                 N'Other',                                                                                                                                                                                                                                                                                        NULL,               N'Other', N'OTH', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8113693, current_timestamp, 1, current_timestamp, 1, 0, N'Previous Home Address',                                                                                                                                                                                                                                                                                        NULL, N'PreviousHomeAddress', N'PHA', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[PatientAddressTypeLkp] ( [PatientAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9203167, current_timestamp, 1, current_timestamp, 1, 0,             N'Temporary',                                                                                                                                                                                                                                                                                        NULL,           N'Temporary', N'TMP', 1000, '1/1/1900',        NULL, 0, 0 )

GO
