
print '------------------------------------------------------------------------------------------'
print 'PatientModule_EducationStatusLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1249823, current_timestamp, 1, current_timestamp, 1, 0,                           N'7 Years Completed', NULL,  N'YR7',  N'YR7',    8, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1433648, current_timestamp, 1, current_timestamp, 1, 0,               N'Less than one grade completed', NULL,  N'YR0',  N'YR0',    1, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1452378, current_timestamp, 1, current_timestamp, 1, 0,                           N'8 Years Completed', NULL,  N'YR8',  N'YR8',    9, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1684475, current_timestamp, 1, current_timestamp, 1, 0,                        N'Post Graduate 1 Year', NULL, N'YR17', N'YR17',   18, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1939066, current_timestamp, 1, current_timestamp, 1, 0,                       N'Post Secondary 1 Year', NULL, N'YR13', N'YR13',   14, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2588371, current_timestamp, 1, current_timestamp, 1, 0,                           N'5 Years Completed', NULL,  N'YR5',  N'YR5',    6, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2849331, current_timestamp, 1, current_timestamp, 1, 0,                           N'4 Years Completed', NULL,  N'YR4',  N'YR4',    5, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3431163, current_timestamp, 1, current_timestamp, 1, 0,                            N'1 Year Completed', NULL,  N'YR1',  N'YR1',    2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3864752, current_timestamp, 1, current_timestamp, 1, 0,                           N'6 Years Completed', NULL,  N'YR6',  N'YR6',    7, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4261976, current_timestamp, 1, current_timestamp, 1, 0,                N'Baccalaureate Degree (BA,BS)', NULL, N'YR16', N'YR16',   17, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4271526, current_timestamp, 1, current_timestamp, 1, 0, N'Post Graduate 4 Years (including Master''s)', NULL, N'YR20', N'YR20',   21, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4878022, current_timestamp, 1, current_timestamp, 1, 0,                          N'11 Years Completed', NULL, N'YR11', N'YR11',   12, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5700317, current_timestamp, 1, current_timestamp, 1, 0,                           N'2 Years Completed', NULL,  N'YR2',  N'YR2',    3, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6138467, current_timestamp, 1, current_timestamp, 1, 0,          N'Post Secondary 2 Years / AA Degree', NULL, N'YR14', N'YR14',   15, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6361380, current_timestamp, 1, current_timestamp, 1, 0,                           N'9 Years Completed', NULL,  N'YR9',  N'YR9',   10, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6372274, current_timestamp, 1, current_timestamp, 1, 0,                           N'3 Years Completed', NULL,  N'YR3',  N'YR3',    4, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7089261, current_timestamp, 1, current_timestamp, 1, 0,                       N'Post Graduate 6 Years', NULL, N'YR22', N'YR22',   23, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7089275, current_timestamp, 1, current_timestamp, 1, 0,                       N'Post Graduate 3 Years', NULL, N'YR19', N'YR19',   20, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7166062, current_timestamp, 1, current_timestamp, 1, 0,                   N'Post Graduate 7 Years    ', NULL, N'YR23', N'YR23',   24, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7166091, current_timestamp, 1, current_timestamp, 1, 0, N'Post Graduate 2 Years (including Master''s)', NULL, N'YR18', N'YR18',   19, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7275518, current_timestamp, 1, current_timestamp, 1, 0,                    N'12 Years Completed / GED', NULL, N'YR12', N'YR12',   13, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7275563, current_timestamp, 1, current_timestamp, 1, 0,                   N'Post Graduate 8 Years    ', NULL, N'YR24', N'YR24',   25, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8941939, current_timestamp, 1, current_timestamp, 1, 0,                          N'10 Years Completed', NULL, N'YR10', N'YR10',   11, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8941964, current_timestamp, 1, current_timestamp, 1, 0,                   N'Post Graduate 9 Years    ', NULL, N'YR25', N'YR25',   26, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9570265, current_timestamp, 1, current_timestamp, 1, 0,                                     N'Unknown', NULL,  N'UKN',  N'UKN', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PatientModule].[EducationStatusLkp] ( [EducationStatusLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9570278, current_timestamp, 1, current_timestamp, 1, 0,                      N'Post Secondary 3 Years', NULL, N'YR15', N'YR15',   16, '1/1/1900',        NULL, 0, 0 )

GO
