
print '------------------------------------------------------------------------------------------'
print 'PayorModule_PayorAddressTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [PayorModule].[PayorAddressTypeLkp] ( [PayorAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1456680, current_timestamp, 1, current_timestamp, 1, 0,               N'Billing',                                                                                                                                                                                                                                                                                        NULL,  N'BL',  N'BL', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PayorModule].[PayorAddressTypeLkp] ( [PayorAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3664656, current_timestamp, 1, current_timestamp, 1, 0,           N'Work/Office',                                                                                                                                                                                                     N'An office address. First choice for business related contacts during business hours.',  N'WO',  N'WO',    2, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PayorModule].[PayorAddressTypeLkp] ( [PayorAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6219671, current_timestamp, 1, current_timestamp, 1, 0,               N'Mailing',                                                                                                                                                                                                                                                                                        NULL,  N'HL',  N'HL', 1000, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [PayorModule].[PayorAddressTypeLkp] ( [PayorAddressTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7816849, current_timestamp, 1, current_timestamp, 1, 0,                 N'Other',                                                                                                                                                                                                                                                                                        NULL, N'OTH', N'OTH', 1000, '1/1/1900',        NULL, 0, 0 )

GO
