
print '------------------------------------------------------------------------------------------'
print 'RadiologyModule_RadiologyTestTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91920, current_timestamp, 1, current_timestamp, 1, 0,                                    N'DXA scan (Bone Density test)', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91921, current_timestamp, 1, current_timestamp, 1, 0,                                      N'MRI without contrast, neck', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91922, current_timestamp, 1, current_timestamp, 1, 0,                                             N'Chest X-ray 2 views', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91923, current_timestamp, 1, current_timestamp, 1, 0,                                             N'Chest X-ray 4 views', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91924, current_timestamp, 1, current_timestamp, 1, 0,     N'X-ray: AP Pelvis, Anteroposterior ( AP) & Lateral/Right Hip', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )
INSERT INTO [RadiologyModule].[RadiologyTestTypeLkp] ( [RadiologyTestTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 91925, current_timestamp, 1, current_timestamp, 1, 0, N'X-ray: AP Pelvis, Anteroposterior ( AP) & Lateral/Bilateral Hip', NULL, NULL, NULL, NULL, '1/1/1900',        NULL, 0, 0 )

GO
