print '------------------------------------------------------------------------------------------'
print 'TedsModule_PriorTreatmentEpisodesCountTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'0 previous episodes', NULL, N'0 previous episodes', N'0', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'1 previous episode', NULL, N'1 previous episode', N'1', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'2 previous episodes', NULL, N'2 previous episodes', N'2', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'3 previous episodes', NULL, N'3 previous episodes', N'3', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'4 previous episodes', NULL, N'4 previous episodes', N'4', NULL, 5, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PriorTreatmentEpisodesCountTypeLkp] ( [PriorTreatmentEpisodesCountTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'5 or more previous episodes', NULL, N'5 or more previous episodes', N'5', NULL, 6, '1/1/1900',NULL, 0, 0 )

GO