print '------------------------------------------------------------------------------------------'
print 'TedsModule_SubstanceProblemTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'None', NULL, N'None', N'01', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'Alcohol', NULL, N'Alcohol', N'02', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Cocaine/Crack', NULL, N'Cocaine/Crack', N'03', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Marijuana/Hashish', NULL, N'Marijuana/Hashish', N'04', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Heroin', NULL, N'Heroin', N'05', NULL, 5, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'Non-Prescription Methadone', NULL, N'Non-Prescription Methadone', N'06', NULL, 6, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0, N'Other Opiates And Synthetics', NULL, N'Other Opiates And Synthetics', N'07', NULL, 7, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0, N'PCP-phencyclidine', NULL, N'PCP-phencyclidine', N'08', NULL, 8, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9, current_timestamp, 1, current_timestamp, 1, 0, N'Other Hallucinogens', NULL, N'Other Hallucinogens', N'09', NULL, 9, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 0, N'Methamphetamine', NULL, N'Methamphetamine', N'10', NULL, 10, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 0, N'Other Amphetamines', NULL, N'Other Amphetamines', N'11', NULL, 11, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 0, N'Other Stimulants', NULL, N'Other Stimulants', N'12', NULL, 12, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 0, N'Benzodiazepine', NULL, N'Benzodiazepine', N'13', NULL, 13, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 14, current_timestamp, 1, current_timestamp, 1, 0, N'Other non-Benzodiazepine Tranquilizers', NULL, N'Other non-Benzodiazepine Tranquilizers', N'14', NULL, 14, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 15, current_timestamp, 1, current_timestamp, 1, 0, N'Barbiturates', NULL, N'Barbiturates', N'15', NULL, 15, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 16, current_timestamp, 1, current_timestamp, 1, 0, N'Other Non-Barbiturate Sedatives or Hypnotics', NULL, N'Other Non-Barbiturate Sedatives or Hypnotics', N'16', NULL, 16, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 17, current_timestamp, 1, current_timestamp, 1, 0, N'Inhalants', NULL, N'Inhalants', N'17', NULL, 17, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 18, current_timestamp, 1, current_timestamp, 1, 0, N'Over-The-Counter', NULL, N'Over-The-Counter', N'18', NULL, 18, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[SubstanceProblemTypeLkp] ( [SubstanceProblemTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 19, current_timestamp, 1, current_timestamp, 1, 0, N'Other', NULL, N'Other', N'20', NULL, 19, '1/1/1900',NULL, 0, 0 )

GO