
print '------------------------------------------------------------------------------------------'
print 'TedsModule_UseFrequencyTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[UseFrequencyTypeLkp] ( [UseFrequencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'No use in the past month', NULL, N'No use in the past month', N'01', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[UseFrequencyTypeLkp] ( [UseFrequencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'1-3 times in the past month', NULL, N'1-3 times in the past month', N'02', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[UseFrequencyTypeLkp] ( [UseFrequencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'1-2 times in the past week', NULL, N'1-2 times in the past week', N'03', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[UseFrequencyTypeLkp] ( [UseFrequencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'3-6 times in the past week', NULL, N'3-6 times in the past week', N'04', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[UseFrequencyTypeLkp] ( [UseFrequencyTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Daily', NULL, N'Daily', N'05', NULL, 5, '1/1/1900',NULL, 0, 0 )

GO