print '------------------------------------------------------------------------------------------'
print 'TedsModule_TedsDischargeReasonLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'Treatment completed', NULL, N'Treatment completed', N'01', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'Left against  professional advice including drop-out', NULL, N'Left against  professional advice including drop-out', N'02', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Terminated by facility', NULL, N'Terminated by facility', N'03', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Transferred to other SA treatment program or facility', NULL, N'Transferred to other SA treatment program or facility', N'04', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Transferred to other SA treatment program or facility, did not report', NULL, N'Transferred to other SA treatment program or facility, did not report', N'14', NULL, 5, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'Incarcerated', NULL, N'Incarcerated', N'05', NULL, 6, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0, N'Death', NULL, N'Death', N'06', NULL, 7, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsDischargeReasonLkp] ( [TedsDischargeReasonLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0, N'Other', NULL, N'Other', N'07', NULL, 8, '1/1/1900',NULL, 0, 0 )

GO