
print '------------------------------------------------------------------------------------------'
print 'TedsModule_PrimaryPaymentSourceTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'Self-Pay', NULL, N'Self-Pay', N'01', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'Blue Cross/Blue Shield', NULL, N'Blue Cross/Blue Shield', N'02', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Medicare', NULL, N'Medicare', N'03', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Medicaid', NULL, N'Medicaid', N'04', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Other Government Payments', NULL, N'Other Government Payments', N'05', NULL, 5, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'Worker''s Compensation', NULL, N'Worker''s Compensation', N'06', NULL, 6, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 7, current_timestamp, 1, current_timestamp, 1, 0, N'Other Health Insurance Companies', NULL, N'Other Health Insurance Companies', N'07', NULL, 7, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 8, current_timestamp, 1, current_timestamp, 1, 0, N'No Charge (Free, Charity, Special Research Or Teaching)', NULL, N'No Charge (Free, Charity, Special Research Or Teaching)', N'08', NULL, 8, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[PrimaryPaymentSourceTypeLkp] ( [PrimaryPaymentSourceTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 9, current_timestamp, 1, current_timestamp, 1, 0, N'Other', NULL, N'Other', N'09', NULL, 9, '1/1/1900',NULL, 0, 0 )

GO