
print '------------------------------------------------------------------------------------------'
print 'TedsModule_TedsEthnicityLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 1, current_timestamp, 1, current_timestamp, 1, 0, N'Puerto Rican', NULL, N'Puerto Rican', N'01', NULL, 1, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 2, current_timestamp, 1, current_timestamp, 1, 0, N'Mexican', NULL, N'Mexican', N'02', NULL, 2, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 3, current_timestamp, 1, current_timestamp, 1, 0, N'Cuban', NULL, N'Cuban', N'03', NULL, 3, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 4, current_timestamp, 1, current_timestamp, 1, 0, N'Other Specific Hispanic', NULL, N'Other Specific Hispanic', N'04', NULL, 4, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 5, current_timestamp, 1, current_timestamp, 1, 0, N'Not of Hispanic Origin', NULL, N'Not of Hispanic Origin', N'05', NULL, 5, '1/1/1900',NULL, 0, 0 )
INSERT INTO [TedsModule].[TedsEthnicityLkp] ( [TedsEthnicityLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [Code], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator]  ) VALUES ( 6, current_timestamp, 1, current_timestamp, 1, 0, N'Hispanic - specific origin unknown', NULL, N'Hispanic - specific origin unknown', N'06', NULL, 6, '1/1/1900',NULL, 0, 0 )

GO