
print '------------------------------------------------------------------------------------------'
print 'VisitModule_ActivityTypeLkp.sql'
print '------------------------------------------------------------------------------------------'

INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 1,  current_timestamp, 1, current_timestamp, 1, 0,					N'Vital Sign',  N'',				  N'VitalSign',					 N'VitalSign', 0,  '6/9/2010', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 2,  current_timestamp, 1, current_timestamp, 1, 0,				  N'Lab Specimen',  N'',				N'LabSpecimen',				   N'LabSpecimen', 0,  '6/9/2010', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 3,  current_timestamp, 1, current_timestamp, 1, 0,			   N'Radiology Order',  N'',			 N'RadiologyOrder',				N'RadiologyOrder', 0,  '6/9/2010', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 4,  current_timestamp, 1, current_timestamp, 1, 0,				  N'Immunization',  N'',			   N'Immunization',				  N'Immunization', 0,  '7/6/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 5,  current_timestamp, 1, current_timestamp, 1, 0,				N'Social History',  N'',			  N'SocialHistory',				 N'SocialHistory', 0,  '7/6/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 6,  current_timestamp, 1, current_timestamp, 1, 0,			N'Brief Intervention',  N'',          N'BriefIntervention',			 N'BriefIntervention', 0, '7/19/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 7,  current_timestamp, 1, current_timestamp, 1, 0,					   N'AUDIT-C',  N'',				    N'AUDIT-C',					   N'AUDIT-C', 0, '7/26/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 8,  current_timestamp, 1, current_timestamp, 1, 0,		    			 N'PHQ-9',  N'',				      N'PHQ-9',						 N'PHQ-9', 0, '7/26/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 9,  current_timestamp, 1, current_timestamp, 1, 0,		 N'Individual Counseling',  N'',	   N'IndividualCounseling',		  N'IndividualCounseling', 0, '7/28/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 10, current_timestamp, 1, current_timestamp, 1, 0,					   N'DAST-10',  N'',				    N'DAST-10',					   N'DAST-10', 0, '7/29/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 11, current_timestamp, 1, current_timestamp, 1, 0,	   N'NIDA Drug Questionnaire',  N'',      N'NidaDrugQuestionnaire',	     N'NidaDrugQuestionnaire', 0,  '8/2/2011', NULL, 1, 0, 0 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 12, current_timestamp, 1, current_timestamp, 1, 0,		        N'GPRA Interview',  N'',			  N'GpraInterview',		         N'GpraInterview', 0,  '8/2/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 13, current_timestamp, 1, current_timestamp, 1, 0,		    N'DENS-ASI Interview',  N'',	       N'DensAsiInterview',		      N'DensAsiInterview', 0, '8/23/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 14, current_timestamp, 1, current_timestamp, 1, 0,		   N'GAIN Short Screener',  N'',	      N'GainShortScreener',		     N'GainShortScreener', 0, '8/23/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 15, current_timestamp, 1, current_timestamp, 1, 0,					     N'AUDIT',  N'',				      N'AUDIT',					     N'AUDIT', 0, '9/13/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 16, current_timestamp, 1, current_timestamp, 1, 0,	  N'TEDS Admission Interview',  N'',     N'TedsAdmissionInterview',	    N'TedsAdmissionInterview', 0, '9/13/2011', NULL, 1, 0, 1 )
INSERT INTO [VisitModule].[ActivityTypeLkp] ( [ActivityTypeLkpKey], [CreatedTimestamp], [CreatedBySystemAccountKey], [UpdatedTimestamp], [UpdatedBySystemAccountKey], [Version], [Name], [Description], [WellKnownName], [ShortName], [SortOrderNumber], [EffectiveStartDate], [EffectiveEndDate], [SystemOwnedIndicator], [DefaultIndicator], [CanBeScheduledIndicator] ) VALUES ( 17, current_timestamp, 1, current_timestamp, 1, 0,	  N'TEDS Discharge Interview',  N'',     N'TedsDischargeInterview',	    N'TedsDischargeInterview', 0, '9/13/2011', NULL, 1, 0, 1 )
GO
