CREATE TABLE [TedsModule].[TedsAdmissionRecord] (
    [TedsAdmissionRecordKey]                                             BIGINT             NOT NULL,
    [Version]                                                            INT                NOT NULL,
    [BirthDate]                                                          DATE               NULL,
    [CreatedTimestamp]                                                   DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                   DATETIMEOFFSET (7) NOT NULL,
    [TedsAdmissionBatchKey]                                              BIGINT             NULL,
    [PrimaryTedsAdmissionRecordSubstanceUsageKey]                        BIGINT             NULL,
    [SecondaryTedsAdmissionRecordSubstanceUsageKey]                      BIGINT             NULL,
    [TertiaryTedsAdmissionRecordSubstanceUsageKey]                       BIGINT             NULL,
    [CreatedBySystemAccountKey]                                          BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                          BIGINT             NOT NULL,
    [AdmissionDate]                                                      DATE               NULL,
    [CoDependentIndicator]                                               BIT                NULL,
    [ClientTransactionTypeLkpKey]                                        BIGINT             NULL,
    [ReportingDate]                                                      DATE               NULL,
    [SystemTransactionTypeLkpKey]                                        BIGINT             NULL,
    [StateProvinceLkpKey]                                                BIGINT             NULL,
    [ProviderIdentifierIdentifierValue]                                  NVARCHAR (255)     NULL,
    [ClientIdentifierIdentifierValue]                                    NVARCHAR (255)     NULL,
    [TedsServiceTypeLkpKey]                                              BIGINT             NULL,
    [TedsServiceTypeTedsNonResponseLkpKey]                               BIGINT             NULL,
    [PriorTreatmentEpisodesCount]                                        INT                NULL,
    [PriorTreatmentEpisodesCountTedsNonResponseLkpKey]                   BIGINT             NULL,
    [PrincipalReferralSourceTypeLkpKey]                                  BIGINT             NULL,
    [PrincipalReferralSourceTypeTedsNonResponseLkpKey]                   BIGINT             NULL,
    [DetailedCriminalJusticeReferralLkpKey]                              BIGINT             NULL,
    [DetailedCriminalJusticeReferralTedsNonResponseLkpKey]               BIGINT             NULL,
    [TedsGenderLkpKey]                                                   BIGINT             NULL,
    [TedsGenderTedsNonResponseLkpKey]                                    BIGINT             NULL,
    [PregnantIndicator]                                                  BIT                NULL,
    [PregnantIndicatorTedsNonResponseLkpKey]                             BIGINT             NULL,
    [TedsRaceLkpKey]                                                     BIGINT             NULL,
    [TedsRaceTedsNonResponseLkpKey]                                      BIGINT             NULL,
    [TedsEthnicityLkpKey]                                                BIGINT             NULL,
    [TedsEthnicityTedsNonResponseLkpKey]                                 BIGINT             NULL,
    [TedsEducationYearCount]                                             INT                NULL,
    [TedsEducationYearCountTedsNonResponseLkpKey]                        BIGINT             NULL,
    [TedsEmploymentStatusLkpKey]                                         BIGINT             NULL,
    [TedsEmploymentStatusTedsNonResponseLkpKey]                          BIGINT             NULL,
    [DetailedNotInLaborForceLkpKey]                                      BIGINT             NULL,
    [DetailedNotInLaborForceTedsNonResponseLkpKey]                       BIGINT             NULL,
    [MedicationAssistedOpioidTherapyIndicator]                           BIT                NULL,
    [MedicationAssistedOpioidTherapyIndicatorTedsNonResponseLkpKey]      BIGINT             NULL,
    [DsmDiagnosisTedsNonResponseLkpKey]                                  BIGINT             NULL,
    [DsmDiagnosisResponseCode]                                           NVARCHAR (10)      NULL,
    [OtherPsychiatricProblemIndicator]                                   BIT                NULL,
    [OtherPsychiatricProblemIndicatorTedsNonResponseLkpKey]              BIGINT             NULL,
    [VeteranStatusIndicator]                                             BIT                NULL,
    [VeteranStatusIndicatorTedsNonResponseLkpKey]                        BIGINT             NULL,
    [LivingArrangementsTypeLkpKey]                                       BIGINT             NULL,
    [LivingArrangementsTypeTedsNonResponseLkpKey]                        BIGINT             NULL,
    [IncomeSourceTypeLkpKey]                                             BIGINT             NULL,
    [IncomeSourceTypeTedsNonResponseLkpKey]                              BIGINT             NULL,
    [HealthInsuranceTypeLkpKey]                                          BIGINT             NULL,
    [HealthInsuranceTypeTedsNonResponseLkpKey]                           BIGINT             NULL,
    [PrimaryPaymentSourceTypeLkpKey]                                     BIGINT             NULL,
    [PrimaryPaymentSourceTypeTedsNonResponseLkpKey]                      BIGINT             NULL,
    [MaritalStatusLkpKey]                                                BIGINT             NULL,
    [MaritalStatusTedsNonResponseLkpKey]                                 BIGINT             NULL,
    [DaysWaitingToEnterTreatmentCount]                                   INT                NULL,
    [DaysWaitingToEnterTreatmentCountTedsNonResponseLkpKey]              BIGINT             NULL,
    [ArrestsInThirtyDaysCount]                                           INT                NULL,
    [ArrestsInThirtyDaysCountTedsNonResponseLkpKey]                      BIGINT             NULL,
    [ParticipatedSelfHelpGroupInPastThirtyDaysTypeLkpKey]                BIGINT             NULL,
    [ParticipatedSelfHelpGroupInPastThirtyDaysTypeTedsNonResponseLkpKey] BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([TedsAdmissionRecordKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





