CREATE TABLE [GpraModule].[GpraProblemsTreatmentRecovery] (
    [GpraInterviewKey]                                                    BIGINT             NOT NULL,
    [CreatedTimestamp]                                                    DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                    DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                           BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                           BIGINT             NOT NULL,
    [InpatientPhysicalComplaintIndicator]                                 BIT                NULL,
    [InpatientMentalEmotionalDifficultiesIndicator]                       BIT                NULL,
    [InpatientAlcoholSubstanceAbuseIndicator]                             BIT                NULL,
    [OutpatientPhysicalComplaintIndicator]                                BIT                NULL,
    [OutpatientMentalEmotionalDifficultiesIndicator]                      BIT                NULL,
    [OutpatientAlcoholSubstanceAbuseIndicator]                            BIT                NULL,
    [ErPhysicalComplaintIndicator]                                        BIT                NULL,
    [ErMentalEmotionalDifficultiesIndicator]                              BIT                NULL,
    [ErAlcoholSubstanceAbuseIndicator]                                    BIT                NULL,
    [HivTestResultsKnownIndicator]                                        BIT                NULL,
    [GpraOverallHealthLkpKey]                                             BIGINT             NULL,
    [GpraOverallHealthGpraNonResponseLkpKey]                              BIGINT             NULL,
    [InpatientPhysicalComplaintNightCount]                                INT                NULL,
    [InpatientPhysicalComplaintNightCountGpraNonResponseLkpKey]           BIGINT             NULL,
    [InpatientMentalEmotionalDifficultiesNightCount]                      INT                NULL,
    [InpatientMentalEmotionalDifficultiesNightCountGpraNonResponseLkpKey] BIGINT             NULL,
    [InpatientAlcoholSubstanceAbuseNightCount]                            INT                NULL,
    [InpatientAlcoholSubstanceAbuseNightCountGpraNonResponseLkpKey]       BIGINT             NULL,
    [OutpatientPhysicalComplaintTimeCount]                                INT                NULL,
    [OutpatientPhysicalComplaintTimeCountGpraNonResponseLkpKey]           BIGINT             NULL,
    [OutpatientMentalEmotionalDifficultiesTimeCount]                      INT                NULL,
    [OutpatientMentalEmotionalDifficultiesTimeCountGpraNonResponseLkpKey] BIGINT             NULL,
    [OutpatientAlcoholSubstanceAbuseTimeCount]                            INT                NULL,
    [OutpatientAlcoholSubstanceAbuseTimeCountGpraNonResponseLkpKey]       BIGINT             NULL,
    [ErPhysicalComplaintTimeCount]                                        INT                NULL,
    [ErPhysicalComplaintTimeCountGpraNonResponseLkpKey]                   BIGINT             NULL,
    [ErMentalEmotionalDifficultiesTimeCount]                              INT                NULL,
    [ErMentalEmotionalDifficultiesTimeCountGpraNonResponseLkpKey]         BIGINT             NULL,
    [ErAlcoholSubstanceAbuseTimeCount]                                    INT                NULL,
    [ErAlcoholSubstanceAbuseTimeCountGpraNonResponseLkpKey]               BIGINT             NULL,
    [GpraSexualActivityLkpKey]                                            BIGINT             NULL,
    [GpraSexualActivityGpraNonResponseLkpKey]                             BIGINT             NULL,
    [SexualContactsCount]                                                 INT                NULL,
    [SexualContactsCountGpraNonResponseLkpKey]                            BIGINT             NULL,
    [UnprotectedSexualContactsCount]                                      INT                NULL,
    [UnprotectedSexualContactsCountGpraNonResponseLkpKey]                 BIGINT             NULL,
    [UnprotectedSexualHivContactsCount]                                   INT                NULL,
    [UnprotectedSexualHivContactsCountGpraNonResponseLkpKey]              BIGINT             NULL,
    [UnprotectedSexualInjectionDrugContactsCount]                         INT                NULL,
    [UnprotectedSexualInjectionDrugContactsCountGpraNonResponseLkpKey]    BIGINT             NULL,
    [UnprotectedSexualHighSaContactsCount]                                INT                NULL,
    [UnprotectedSexualHighSaContactsCountGpraNonResponseLkpKey]           BIGINT             NULL,
    [HivTestIndicator]                                                    BIT                NULL,
    [HivTestIndicatorGpraNonResponseLkpKey]                               BIGINT             NULL,
    [DepressionDayCount]                                                  INT                NULL,
    [DepressionDayCountGpraNonResponseLkpKey]                             BIGINT             NULL,
    [AnxietyDayCount]                                                     INT                NULL,
    [AnxietyDayCountGpraNonResponseLkpKey]                                BIGINT             NULL,
    [HallucinationsDayCount]                                              INT                NULL,
    [HallucinationsDayCountGpraNonResponseLkpKey]                         BIGINT             NULL,
    [BrainMisfunctionDayCount]                                            INT                NULL,
    [BrainMisfunctionDayCountGpraNonResponseLkpKey]                       BIGINT             NULL,
    [ViolentBehaviorDayCount]                                             INT                NULL,
    [ViolentBehaviorDayCountGpraNonResponseLkpKey]                        BIGINT             NULL,
    [SuicideDayCount]                                                     INT                NULL,
    [SuicideDayCountGpraNonResponseLkpKey]                                BIGINT             NULL,
    [PsychologicalEmotionalMedicationDayCount]                            INT                NULL,
    [PsychologicalEmotionalMedicationDayCountGpraNonResponseLkpKey]       BIGINT             NULL,
    [GpraPsychologicalImpactLkpKey]                                       BIGINT             NULL,
    [GpraPsychologicalImpactGpraNonResponseLkpKey]                        BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([GpraInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);







