CREATE TABLE [GpraModule].[GpraPlannedServices] (
    [GpraInterviewKey]                                           BIGINT             NOT NULL,
    [CreatedTimestamp]                                           DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                           DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                  BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                  BIGINT             NOT NULL,
    [ModalityCaseMgmtIndicator]                                  BIT                NULL,
    [ModalityDayTreatmentIndicator]                              BIT                NULL,
    [ModalityInpatientHospitalIndicator]                         BIT                NULL,
    [ModalityOutpatientIndicator]                                BIT                NULL,
    [ModalityOutreachIndicator]                                  BIT                NULL,
    [ModalityIntensiveOutpatientIndicator]                       BIT                NULL,
    [ModalityMethadoneIndicator]                                 BIT                NULL,
    [ModalityResidentialRehabilitationIndicator]                 BIT                NULL,
    [ModalityAfterCareIndicator]                                 BIT                NULL,
    [ModalityRecoverySupportIndicator]                           BIT                NULL,
    [ModalityOtherSpecificationIndicator]                        BIT                NULL,
    [ModalitySpecificationNote]                                  NVARCHAR (MAX)     NULL,
    [TreatmentScreeningIndicator]                                BIT                NULL,
    [TreatmentBriefInterventionIndicator]                        BIT                NULL,
    [TreatmentBriefTreatmentIndicator]                           BIT                NULL,
    [TreatmentReferralToTreatmentIndicator]                      BIT                NULL,
    [TreatmentAssessmentIndicator]                               BIT                NULL,
    [TreatmentRecoveryPlanningIndicator]                         BIT                NULL,
    [TreatmentIndividualCounselingIndicator]                     BIT                NULL,
    [TreatmentGroupCounselingIndicator]                          BIT                NULL,
    [TreatmentFamilyCounselingIndicator]                         BIT                NULL,
    [TreatmentCooccuringTreatmentIndicator]                      BIT                NULL,
    [TreatmentPharmacologicalInterventionsIndicator]             BIT                NULL,
    [TreatmentHivAidsCounselingIndicator]                        BIT                NULL,
    [TreatmentOtherSpecificationIndicator]                       BIT                NULL,
    [TreatmentSpecificationNote]                                 NVARCHAR (MAX)     NULL,
    [CaseMgmtFamilyServicesIndicator]                            BIT                NULL,
    [CaseMgmtChildCareIndicator]                                 BIT                NULL,
    [CaseMgmtPreemploymentIndicator]                             BIT                NULL,
    [CaseMgmtEmploymentCoachingIndicator]                        BIT                NULL,
    [CaseMgmtIndividualServicesCoordinationIndicator]            BIT                NULL,
    [CaseMgmtTransportationIndicator]                            BIT                NULL,
    [CaseMgmtHivAidsServiceIndicator]                            BIT                NULL,
    [CaseMgmtTransitionalDrugFreeHousingIndicator]               BIT                NULL,
    [CaseMgmtOtherIndicator]                                     BIT                NULL,
    [CaseMgmtSpecificationNote]                                  NVARCHAR (MAX)     NULL,
    [MedicalCareIndicator]                                       BIT                NULL,
    [MedicalAlcoholDrugTestIndicator]                            BIT                NULL,
    [MedicalHivAidsSupportAndTestingIndicator]                   BIT                NULL,
    [MedicalOtherIndicator]                                      BIT                NULL,
    [MedicalSpecificationNote]                                   NVARCHAR (MAX)     NULL,
    [AfterCareContinuingCareIndicator]                           BIT                NULL,
    [AfterCareReplasePreventionIndicator]                        BIT                NULL,
    [AfterCareRecoveryCoachingIndicator]                         BIT                NULL,
    [AfterCareSelfHelpSupportGroupsIndicator]                    BIT                NULL,
    [AfterCareSpiritualSupportIndicator]                         BIT                NULL,
    [AfterCareOtherIndicator]                                    BIT                NULL,
    [AfterCareSpecificationNote]                                 NVARCHAR (MAX)     NULL,
    [EducationSaIndicator]                                       BIT                NULL,
    [EducationHivAidsIndicator]                                  BIT                NULL,
    [EducationOtherIndicator]                                    BIT                NULL,
    [EducationSpecificationNote]                                 NVARCHAR (MAX)     NULL,
    [PeerToPeerRecoverySupportCoachingIndicator]                 BIT                NULL,
    [PeerToPeerRecoverySupportHousingIndicator]                  BIT                NULL,
    [PeerToPeerRecoverySupportAlcholDrugFreeActivitiesIndicator] BIT                NULL,
    [PeerToPeerRecoverySupportInformationReferralIndicator]      BIT                NULL,
    [PeerToPeerRecoverySupportOtherIndicator]                    BIT                NULL,
    [PeerToPeerRecoverySupportSpecificationNote]                 NVARCHAR (MAX)     NULL,
    [ModalityGpraDetoxificationLocationLkpKey]                   BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([GpraInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





