CREATE TABLE [DensAsiModule].[DensAsiDrugAlcoholUse] (
    [DensAsiInterviewKey]                                                              BIGINT             NOT NULL,
    [CreatedTimestamp]                                                                 DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                                 DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                                        BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                                        BIGINT             NOT NULL,
    [AnyAlcoholUseNote]                                                                NVARCHAR (MAX)     NULL,
    [AlcoholIntoxicationNote]                                                          NVARCHAR (MAX)     NULL,
    [HeroinNote]                                                                       NVARCHAR (MAX)     NULL,
    [MethadoneNote]                                                                    NVARCHAR (MAX)     NULL,
    [OtherOpiatesNote]                                                                 NVARCHAR (MAX)     NULL,
    [BarbituratesNote]                                                                 NVARCHAR (MAX)     NULL,
    [OtherSedativesNote]                                                               NVARCHAR (MAX)     NULL,
    [CocaineNote]                                                                      NVARCHAR (MAX)     NULL,
    [AmphetaminesNote]                                                                 NVARCHAR (MAX)     NULL,
    [CannabisNote]                                                                     NVARCHAR (MAX)     NULL,
    [HallucinogensNote]                                                                NVARCHAR (MAX)     NULL,
    [InhalantsNote]                                                                    NVARCHAR (MAX)     NULL,
    [MoreThanOneSubstancePerDayNote]                                                   NVARCHAR (MAX)     NULL,
    [MajorDensAsiProblematicSubstanceNote]                                             NVARCHAR (MAX)     NULL,
    [VoluntaryAbstinenceFromProblematicSubstanceMonthCountNote]                        NVARCHAR (MAX)     NULL,
    [EndOfProblematicSubstanceAbstinenceMonthCountNote]                                NVARCHAR (MAX)     NULL,
    [AlcoholDtCountNote]                                                               NVARCHAR (MAX)     NULL,
    [OverdosedOnDrugsCountNote]                                                        NVARCHAR (MAX)     NULL,
    [AlcoholAbuseTreatmentCountNote]                                                   NVARCHAR (MAX)     NULL,
    [AlcoholDetoxTreatmentOnlyCountNote]                                               NVARCHAR (MAX)     NULL,
    [MoneySpentOnAlcoholInLastThirtyDaysAmountNote]                                    NVARCHAR (MAX)     NULL,
    [DrugAbuseTreatmentCountNote]                                                      NVARCHAR (MAX)     NULL,
    [DrugDetoxTreatmentOnlyCountNote]                                                  NVARCHAR (MAX)     NULL,
    [MoneySpentOnDrugsInLastThirtyDaysAmountNote]                                      NVARCHAR (MAX)     NULL,
    [OutpatientTreatmentInLastThirtyDaysDayCountNote]                                  NVARCHAR (MAX)     NULL,
    [AlcoholProblemInLastThirtyDaysDayCountNote]                                       NVARCHAR (MAX)     NULL,
    [TroubledByAlcoholProblemsDensAsiPatientRatingNote]                                NVARCHAR (MAX)     NULL,
    [ImportanceOfAlcoholProblemTreatmentDensAsiPatientRatingNote]                      NVARCHAR (MAX)     NULL,
    [DrugProblemInLastThirtyDaysDayCountNote]                                          NVARCHAR (MAX)     NULL,
    [TroubledByDrugProblemsDensAsiPatientRatingNote]                                   NVARCHAR (MAX)     NULL,
    [ImportanceOfDrugProblemTreatmentDensAsiPatientRatingNote]                         NVARCHAR (MAX)     NULL,
    [PatientAlcoholTreatmentDensAsiInterviewerRatingNote]                              NVARCHAR (MAX)     NULL,
    [PatientDrugTreatmentDensAsiInterviewerRatingNote]                                 NVARCHAR (MAX)     NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicator]                           BIT                NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicatorNote]                       NVARCHAR (MAX)     NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicator]                   BIT                NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicatorNote]               NVARCHAR (MAX)     NULL,
    [HydromorphoneNote]                                                                NVARCHAR (MAX)     NULL,
    [OxycodoneNote]                                                                    NVARCHAR (MAX)     NULL,
    [HydrocodoneNote]                                                                  NVARCHAR (MAX)     NULL,
    [BuprenorphineNote]                                                                NVARCHAR (MAX)     NULL,
    [OxyContinNote]                                                                    NVARCHAR (MAX)     NULL,
    [OxyContinPrescribedForMedicalReasonIndicatorNote]                                 NVARCHAR (MAX)     NULL,
    [OxyContinUseToGetHighIndicatorNote]                                               NVARCHAR (MAX)     NULL,
    [OxyContinTakenWithOtherOpiatesIndicatorNote]                                      NVARCHAR (MAX)     NULL,
    [AfterOxyContinFirstUseMonthCountNote]                                             NVARCHAR (MAX)     NULL,
    [OxyContinFromFriendFamilyStreetIndicatorNote]                                     NVARCHAR (MAX)     NULL,
    [SectionNote]                                                                      NVARCHAR (MAX)     NULL,
    [PatientAlcoholTreatmentDensAsiInterviewerRatingLkpKey]                            BIGINT             NULL,
    [PatientDrugTreatmentDensAsiInterviewerRatingLkpKey]                               BIGINT             NULL,
    [AnyAlcoholUseInLastThirtyDaysDayCount]                                            INT                NULL,
    [AnyAlcoholUseInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [AnyAlcoholUseInLifetimeYearCount]                                                 INT                NULL,
    [AnyAlcoholUseInLifetimeYearCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [AnyAlcoholDensAsiDrugAlcoholAdministrationRouteLkpKey]                            BIGINT             NULL,
    [AnyAlcoholDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]          BIGINT             NULL,
    [AlcoholIntoxicationInLastThirtyDaysDayCount]                                      INT                NULL,
    [AlcoholIntoxicationInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]              BIGINT             NULL,
    [AlcoholIntoxicationUseInLifetimeYearCount]                                        INT                NULL,
    [AlcoholIntoxicationUseInLifetimeYearCountDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [AlcoholIntoxicationDensAsiDrugAlcoholAdministrationRouteLkpKey]                   BIGINT             NULL,
    [AlcoholIntoxicationDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey] BIGINT             NULL,
    [HeroinInLastThirtyDaysDayCount]                                                   INT                NULL,
    [HeroinInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [HeroinInLifetimeYearCount]                                                        INT                NULL,
    [HeroinInLifetimeYearCountDensAsiNonResponseLkpKey]                                BIGINT             NULL,
    [HeroinDensAsiDrugAlcoholAdministrationRouteLkpKey]                                BIGINT             NULL,
    [HeroinDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]              BIGINT             NULL,
    [MethadoneInLastThirtyDaysDayCount]                                                INT                NULL,
    [MethadoneInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [MethadoneInLifetimeYearCount]                                                     INT                NULL,
    [MethadoneInLifetimeYearCountDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [MethadoneDensAsiDrugAlcoholAdministrationRouteLkpKey]                             BIGINT             NULL,
    [MethadoneDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]           BIGINT             NULL,
    [OtherOpiatesInLastThirtyDaysDayCount]                                             INT                NULL,
    [OtherOpiatesInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    [OtherOpiatesInLifetimeYearCount]                                                  INT                NULL,
    [OtherOpiatesInLifetimeYearCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [OtherOpiatesDensAsiDrugAlcoholAdministrationRouteLkpKey]                          BIGINT             NULL,
    [OtherOpiatesDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]        BIGINT             NULL,
    [BarbituratesInLastThirtyDaysDayCount]                                             INT                NULL,
    [BarbituratesInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    [BarbituratesInLifetimeYearCount]                                                  INT                NULL,
    [BarbituratesInLifetimeYearCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [BarbituratesDensAsiDrugAlcoholAdministrationRouteLkpKey]                          BIGINT             NULL,
    [BarbituratesDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]        BIGINT             NULL,
    [OtherSedativesInLastThirtyDaysDayCount]                                           INT                NULL,
    [OtherSedativesInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [OtherSedativesInLifetimeYearCount]                                                INT                NULL,
    [OtherSedativesInLifetimeYearCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [OtherSedativesDensAsiDrugAlcoholAdministrationRouteLkpKey]                        BIGINT             NULL,
    [OtherSedativesDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]      BIGINT             NULL,
    [CocaineInLastThirtyDaysDayCount]                                                  INT                NULL,
    [CocaineInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [CocaineInLifetimeYearCount]                                                       INT                NULL,
    [CocaineInLifetimeYearCountDensAsiNonResponseLkpKey]                               BIGINT             NULL,
    [CocaineDensAsiDrugAlcoholAdministrationRouteLkpKey]                               BIGINT             NULL,
    [CocaineDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]             BIGINT             NULL,
    [AmphetaminesInLastThirtyDaysDayCount]                                             INT                NULL,
    [AmphetaminesInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    [AmphetaminesInLifetimeYearCount]                                                  INT                NULL,
    [AmphetaminesInLifetimeYearCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [AmphetaminesDensAsiDrugAlcoholAdministrationRouteLkpKey]                          BIGINT             NULL,
    [AmphetaminesDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]        BIGINT             NULL,
    [CannabisInLastThirtyDaysDayCount]                                                 INT                NULL,
    [CannabisInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [CannabisInLifetimeYearCount]                                                      INT                NULL,
    [CannabisInLifetimeYearCountDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [CannabisDensAsiDrugAlcoholAdministrationRouteLkpKey]                              BIGINT             NULL,
    [CannabisDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [HallucinogensInLastThirtyDaysDayCount]                                            INT                NULL,
    [HallucinogensInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [HallucinogensInLifetimeYearCount]                                                 INT                NULL,
    [HallucinogensInLifetimeYearCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [HallucinogensDensAsiDrugAlcoholAdministrationRouteLkpKey]                         BIGINT             NULL,
    [HallucinogensDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]       BIGINT             NULL,
    [InhalantsInLastThirtyDaysDayCount]                                                INT                NULL,
    [InhalantsInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [InhalantsInLifetimeYearCount]                                                     INT                NULL,
    [InhalantsInLifetimeYearCountDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [InhalantsDensAsiDrugAlcoholAdministrationRouteLkpKey]                             BIGINT             NULL,
    [InhalantsDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]           BIGINT             NULL,
    [MoreThanOneSubstancePerDayInLastThirtyDaysDayCount]                               INT                NULL,
    [MoreThanOneSubstancePerDayInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]       BIGINT             NULL,
    [MoreThanOneSubstancePerDayInLifetimeYearCount]                                    INT                NULL,
    [MoreThanOneSubstancePerDayInLifetimeYearCountDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [MajorDensAsiProblematicSubstanceLkpKey]                                           BIGINT             NULL,
    [MajorDensAsiProblematicSubstanceDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [VoluntaryAbstinenceFromProblematicSubstanceMonthCount]                            INT                NULL,
    [VoluntaryAbstinenceFromProblematicSubstanceMonthCountDensAsiNonResponseLkpKey]    BIGINT             NULL,
    [EndOfProblematicSubstanceAbstinenceMonthCount]                                    INT                NULL,
    [EndOfProblematicSubstanceAbstinenceMonthCountDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [AlcoholDtCount]                                                                   INT                NULL,
    [AlcoholDtCountDensAsiNonResponseLkpKey]                                           BIGINT             NULL,
    [OverdosedOnDrugsCount]                                                            INT                NULL,
    [OverdosedOnDrugsCountDensAsiNonResponseLkpKey]                                    BIGINT             NULL,
    [AlcoholAbuseTreatmentCount]                                                       INT                NULL,
    [AlcoholAbuseTreatmentCountDensAsiNonResponseLkpKey]                               BIGINT             NULL,
    [AlcoholDetoxTreatmentOnlyCount]                                                   INT                NULL,
    [AlcoholDetoxTreatmentOnlyCountDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [MoneySpentOnAlcoholInLastThirtyDaysAmount]                                        INT                NULL,
    [MoneySpentOnAlcoholInLastThirtyDaysAmountDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [DrugAbuseTreatmentCount]                                                          INT                NULL,
    [DrugAbuseTreatmentCountDensAsiNonResponseLkpKey]                                  BIGINT             NULL,
    [DrugDetoxTreatmentOnlyCount]                                                      INT                NULL,
    [DrugDetoxTreatmentOnlyCountDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [MoneySpentOnDrugsInLastThirtyDaysAmount]                                          INT                NULL,
    [MoneySpentOnDrugsInLastThirtyDaysAmountDensAsiNonResponseLkpKey]                  BIGINT             NULL,
    [OutpatientTreatmentInLastThirtyDaysDayCount]                                      INT                NULL,
    [OutpatientTreatmentInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]              BIGINT             NULL,
    [AlcoholProblemInLastThirtyDaysDayCount]                                           INT                NULL,
    [AlcoholProblemInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [TroubledByAlcoholProblemsDensAsiPatientRatingLkpKey]                              BIGINT             NULL,
    [TroubledByAlcoholProblemsDensAsiPatientRatingDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [ImportanceOfAlcoholProblemTreatmentDensAsiPatientRatingLkpKey]                    BIGINT             NULL,
    [ImportanceOfAlcoholProblemTreatmentDensAsiPatientRatingDensAsiNonResponseLkpKey]  BIGINT             NULL,
    [DrugProblemInLastThirtyDaysDayCount]                                              INT                NULL,
    [DrugProblemInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [TroubledByDrugProblemsDensAsiPatientRatingLkpKey]                                 BIGINT             NULL,
    [TroubledByDrugProblemsDensAsiPatientRatingDensAsiNonResponseLkpKey]               BIGINT             NULL,
    [ImportanceOfDrugProblemTreatmentDensAsiPatientRatingLkpKey]                       BIGINT             NULL,
    [ImportanceOfDrugProblemTreatmentDensAsiPatientRatingDensAsiNonResponseLkpKey]     BIGINT             NULL,
    [HydromorphoneInLastThirtyDaysDayCount]                                            INT                NULL,
    [HydromorphoneInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [HydromorphoneInLifetimeYearCount]                                                 INT                NULL,
    [HydromorphoneInLifetimeYearCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [HydromorphoneDensAsiDrugAlcoholAdministrationRouteLkpKey]                         BIGINT             NULL,
    [HydromorphoneDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]       BIGINT             NULL,
    [OxycodoneInLastThirtyDaysDayCount]                                                INT                NULL,
    [OxycodoneInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [OxycodoneInLifetimeYearCount]                                                     INT                NULL,
    [OxycodoneInLifetimeYearCountDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [OxycodoneDensAsiDrugAlcoholAdministrationRouteLkpKey]                             BIGINT             NULL,
    [OxycodoneDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]           BIGINT             NULL,
    [HydrocodoneInLastThirtyDaysDayCount]                                              INT                NULL,
    [HydrocodoneInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [HydrocodoneInLifetimeYearCount]                                                   INT                NULL,
    [HydrocodoneInLifetimeYearCountDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [HydrocodoneDensAsiDrugAlcoholAdministrationRouteLkpKey]                           BIGINT             NULL,
    [HydrocodoneDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]         BIGINT             NULL,
    [BuprenorphineInLastThirtyDaysDayCount]                                            INT                NULL,
    [BuprenorphineInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [BuprenorphineInLifetimeYearCount]                                                 INT                NULL,
    [BuprenorphineInLifetimeYearCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [BuprenorphineDensAsiDrugAlcoholAdministrationRouteLkpKey]                         BIGINT             NULL,
    [BuprenorphineDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]       BIGINT             NULL,
    [OxyContinInLastThirtyDaysDayCount]                                                INT                NULL,
    [OxyContinInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [OxyContinInLifetimeYearCount]                                                     INT                NULL,
    [OxyContinInLifetimeYearCountDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [OxyContinDensAsiDrugAlcoholAdministrationRouteLkpKey]                             BIGINT             NULL,
    [OxyContinDensAsiDrugAlcoholAdministrationRouteDensAsiNonResponseLkpKey]           BIGINT             NULL,
    [OxyContinPrescribedForMedicalReasonIndicator]                                     BIT                NULL,
    [OxyContinPrescribedForMedicalReasonIndicatorDensAsiNonResponseLkpKey]             BIGINT             NULL,
    [OxyContinUseToGetHighIndicator]                                                   BIT                NULL,
    [OxyContinUseToGetHighIndicatorDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [OxyContinTakenWithOtherOpiatesIndicator]                                          BIT                NULL,
    [OxyContinTakenWithOtherOpiatesIndicatorDensAsiNonResponseLkpKey]                  BIGINT             NULL,
    [AfterOxyContinFirstUseMonthCount]                                                 INT                NULL,
    [AfterOxyContinFirstUseMonthCountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [OxyContinFromFriendFamilyStreetIndicator]                                         BIT                NULL,
    [OxyContinFromFriendFamilyStreetIndicatorDensAsiNonResponseLkpKey]                 BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([DensAsiInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);











