CREATE TABLE [DensAsiModule].[DensAsiEmploymentStatus] (
    [DensAsiInterviewKey]                                                                 BIGINT             NOT NULL,
    [CreatedTimestamp]                                                                    DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                                    DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                                           BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                                           BIGINT             NOT NULL,
    [YearsAndMonthsEducationCompletedTimeSpanNote]                                        NVARCHAR (MAX)     NULL,
    [TechnicalEducationCompletedMonthCountNote]                                           NVARCHAR (MAX)     NULL,
    [ProfessionTradeSkillDescription]                                                     NVARCHAR (500)     NULL,
    [ProfessionTradeSkillNote]                                                            NVARCHAR (MAX)     NULL,
    [ValidDriversLicenseIndicatorNote]                                                    NVARCHAR (MAX)     NULL,
    [AutomobileAvailableforUseIndicatorNote]                                              NVARCHAR (MAX)     NULL,
    [YearsAndMonthsOfLongestFullTimeJobTimeSpanNote]                                      NVARCHAR (MAX)     NULL,
    [UsualOrLastOccupationDescription]                                                    NVARCHAR (500)     NULL,
    [UsualOrLastOccupationNote]                                                           NVARCHAR (MAX)     NULL,
    [ContributionOfSomeoneToSupportIndicatorNote]                                         NVARCHAR (MAX)     NULL,
    [ContributionConstituteMajorityOfYourSupportIndicatorNote]                            NVARCHAR (MAX)     NULL,
    [PastThreeYearsDensAsiEmploymentPatternNote]                                          NVARCHAR (MAX)     NULL,
    [WorkInLastThirtyDaysPaidDayCountNote]                                                NVARCHAR (MAX)     NULL,
    [NetIncomeAmountNote]                                                                 NVARCHAR (MAX)     NULL,
    [UnemploymentCompensationAmountNote]                                                  NVARCHAR (MAX)     NULL,
    [WelfareAmountNote]                                                                   NVARCHAR (MAX)     NULL,
    [PensionBenefitsSocialSecurityAmountNote]                                             NVARCHAR (MAX)     NULL,
    [MateFamilyFriendsAmountNote]                                                         NVARCHAR (MAX)     NULL,
    [IllegalAmountNote]                                                                   NVARCHAR (MAX)     NULL,
    [DependentPeopleCountNote]                                                            NVARCHAR (MAX)     NULL,
    [EmploymentProblemsDayCountNote]                                                      NVARCHAR (MAX)     NULL,
    [TroubledByEmploymentProblemsDensAsiPatientRatingNote]                                NVARCHAR (MAX)     NULL,
    [ImportanceOfEmploymentProblemCounselingDensAsiPatientRatingNote]                     NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingNote]                                       NVARCHAR (MAX)     NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicator]                              BIT                NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicatorNote]                          NVARCHAR (MAX)     NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicator]                      BIT                NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicatorNote]                  NVARCHAR (MAX)     NULL,
    [SectionNote]                                                                         NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingLkpKey]                                     BIGINT             NULL,
    [YearsAndMonthsEducationCompletedTimeSpan]                                            BIGINT             NULL,
    [YearsAndMonthsEducationCompletedTimeSpanDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [TechnicalEducationCompletedMonthCount]                                               INT                NULL,
    [TechnicalEducationCompletedMonthCountDensAsiNonResponseLkpKey]                       BIGINT             NULL,
    [ProfessionTradeSkillIndicator]                                                       BIT                NULL,
    [ProfessionTradeSkillIndicatorDensAsiNonResponseLkpKey]                               BIGINT             NULL,
    [ValidDriversLicenseIndicator]                                                        BIT                NULL,
    [ValidDriversLicenseIndicatorDensAsiNonResponseLkpKey]                                BIGINT             NULL,
    [AutomobileAvailableforUseIndicator]                                                  BIT                NULL,
    [AutomobileAvailableforUseIndicatorDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [YearsAndMonthsOfLongestFullTimeJobTimeSpan]                                          BIGINT             NULL,
    [YearsAndMonthsOfLongestFullTimeJobTimeSpanDensAsiNonResponseLkpKey]                  BIGINT             NULL,
    [UsualOrLastDensAsiOccupationTypeLkpKey]                                              BIGINT             NULL,
    [UsualOrLastDensAsiOccupationTypeDensAsiNonResponseLkpKey]                            BIGINT             NULL,
    [ContributionOfSomeoneToSupportIndicator]                                             BIT                NULL,
    [ContributionOfSomeoneToSupportIndicatorDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    [ContributionConstituteMajorityOfYourSupportIndicator]                                BIT                NULL,
    [ContributionConstituteMajorityOfYourSupportIndicatorDensAsiNonResponseLkpKey]        BIGINT             NULL,
    [PastThreeYearsDensAsiEmploymentPatternLkpKey]                                        BIGINT             NULL,
    [PastThreeYearsDensAsiEmploymentPatternDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [WorkInLastThirtyDaysPaidDayCount]                                                    INT                NULL,
    [WorkInLastThirtyDaysPaidDayCountDensAsiNonResponseLkpKey]                            BIGINT             NULL,
    [NetIncomeAmount]                                                                     INT                NULL,
    [NetIncomeAmountDensAsiNonResponseLkpKey]                                             BIGINT             NULL,
    [UnemploymentCompensationAmount]                                                      INT                NULL,
    [UnemploymentCompensationAmountDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [WelfareAmount]                                                                       INT                NULL,
    [WelfareAmountDensAsiNonResponseLkpKey]                                               BIGINT             NULL,
    [PensionBenefitsSocialSecurityAmount]                                                 INT                NULL,
    [PensionBenefitsSocialSecurityAmountDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [MateFamilyFriendsAmount]                                                             INT                NULL,
    [MateFamilyFriendsAmountDensAsiNonResponseLkpKey]                                     BIGINT             NULL,
    [IllegalAmount]                                                                       INT                NULL,
    [IllegalAmountDensAsiNonResponseLkpKey]                                               BIGINT             NULL,
    [DependentPeopleCount]                                                                INT                NULL,
    [DependentPeopleCountDensAsiNonResponseLkpKey]                                        BIGINT             NULL,
    [EmploymentProblemsDayCount]                                                          INT                NULL,
    [EmploymentProblemsDayCountDensAsiNonResponseLkpKey]                                  BIGINT             NULL,
    [TroubledByEmploymentProblemsDensAsiPatientRatingLkpKey]                              BIGINT             NULL,
    [TroubledByEmploymentProblemsDensAsiPatientRatingDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [ImportanceOfEmploymentProblemCounselingDensAsiPatientRatingLkpKey]                   BIGINT             NULL,
    [ImportanceOfEmploymentProblemCounselingDensAsiPatientRatingDensAsiNonResponseLkpKey] BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([DensAsiInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);











