CREATE TABLE [DensAsiModule].[DensAsiLegalStatus] (
    [DensAsiInterviewKey]                                                            BIGINT             NOT NULL,
    [CreatedTimestamp]                                                               DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                               DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                                      BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                                      BIGINT             NOT NULL,
    [AdmissionPromptedByCriminalJusticeSystemIndicatorNote]                          NVARCHAR (MAX)     NULL,
    [ProbationOrParoleIndicatorNote]                                                 NVARCHAR (MAX)     NULL,
    [ArrestedChargedShopliftingCountNote]                                            NVARCHAR (MAX)     NULL,
    [ArrestedChargedProbationParoleViolationCountNote]                               NVARCHAR (MAX)     NULL,
    [ArrestedChargedDrugChargesCountNote]                                            NVARCHAR (MAX)     NULL,
    [ArrestedChargedForgeryCountNote]                                                NVARCHAR (MAX)     NULL,
    [ArrestedChargedWeaponsOffenseCountNote]                                         NVARCHAR (MAX)     NULL,
    [ArrestedChargedBurglaryLarcencyCountNote]                                       NVARCHAR (MAX)     NULL,
    [ArrestedChargedRobberyCountNote]                                                NVARCHAR (MAX)     NULL,
    [ArrestedChargedAssaultCountNote]                                                NVARCHAR (MAX)     NULL,
    [ArrestedChargedArsonCountNote]                                                  NVARCHAR (MAX)     NULL,
    [ArrestedChargedRapeCountNote]                                                   NVARCHAR (MAX)     NULL,
    [ArrestedChargedHomicideManslaughterCountNote]                                   NVARCHAR (MAX)     NULL,
    [ArrestedChargedProstitutionCountNote]                                           NVARCHAR (MAX)     NULL,
    [ArrestedChargedContemptOfCountCountNote]                                        NVARCHAR (MAX)     NULL,
    [ArrestedChargedOtherDescription]                                                NVARCHAR (500)     NULL,
    [ArrestedChargedOtherNote]                                                       NVARCHAR (MAX)     NULL,
    [ArrestChargesResultedInConvictionsCountNote]                                    NVARCHAR (MAX)     NULL,
    [ChargedWithDisorderlyConductCountNote]                                          NVARCHAR (MAX)     NULL,
    [ChargedWithDrivingWhileIntoxicatedCountNote]                                    NVARCHAR (MAX)     NULL,
    [ChargedWithMajorDrivingViolationsCountNote]                                     NVARCHAR (MAX)     NULL,
    [IncarcerationInLifeMonthCountNote]                                              NVARCHAR (MAX)     NULL,
    [IncarcerationLengthMonthCountNote]                                              NVARCHAR (MAX)     NULL,
    [IncarcerationForDensAsiViolationTypeNote]                                       NVARCHAR (MAX)     NULL,
    [PresentlyAwaitingChargesIndicatorNote]                                          NVARCHAR (MAX)     NULL,
    [PresentlyAwaitingChargesForNote]                                                NVARCHAR (MAX)     NULL,
    [IncarceratedInLastThirtyDaysDayCountNote]                                       NVARCHAR (MAX)     NULL,
    [IllegalActivityInLastThirtyDaysDayCountNote]                                    NVARCHAR (MAX)     NULL,
    [SeriousnessOfLegalProblemsDensAsiPatientRatingNote]                             NVARCHAR (MAX)     NULL,
    [ImportanceOfLegalProblemCounselingDensAsiPatientRatingNote]                     NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingNote]                                  NVARCHAR (MAX)     NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicator]                         BIT                NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicatorNote]                     NVARCHAR (MAX)     NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicator]                 BIT                NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicatorNote]             NVARCHAR (MAX)     NULL,
    [SectionNote]                                                                    NVARCHAR (MAX)     NULL,
    [TreatmentMandatoryForCriminalJusticeSystemIndicatorNote]                        NVARCHAR (MAX)     NULL,
    [TreatmentInsteadOfIncarcerationInPrisonIndicatorNote]                           NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingLkpKey]                                BIGINT             NULL,
    [AdmissionPromptedByCriminalJusticeSystemIndicator]                              BIT                NULL,
    [AdmissionPromptedByCriminalJusticeSystemIndicatorDensAsiNonResponseLkpKey]      BIGINT             NULL,
    [ProbationOrParoleIndicator]                                                     BIT                NULL,
    [ProbationOrParoleIndicatorDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [ArrestedChargedShopliftingCount]                                                INT                NULL,
    [ArrestedChargedShopliftingCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [ArrestedChargedProbationParoleViolationCount]                                   INT                NULL,
    [ArrestedChargedProbationParoleViolationCountDensAsiNonResponseLkpKey]           BIGINT             NULL,
    [ArrestedChargedDrugChargesCount]                                                INT                NULL,
    [ArrestedChargedDrugChargesCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [ArrestedChargedForgeryCount]                                                    INT                NULL,
    [ArrestedChargedForgeryCountDensAsiNonResponseLkpKey]                            BIGINT             NULL,
    [ArrestedChargedWeaponsOffenseCount]                                             INT                NULL,
    [ArrestedChargedWeaponsOffenseCountDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    [ArrestedChargedBurglaryLarcencyCount]                                           INT                NULL,
    [ArrestedChargedBurglaryLarcencyCountDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [ArrestedChargedRobberyCount]                                                    INT                NULL,
    [ArrestedChargedRobberyCountDensAsiNonResponseLkpKey]                            BIGINT             NULL,
    [ArrestedChargedAssaultCount]                                                    INT                NULL,
    [ArrestedChargedAssaultCountDensAsiNonResponseLkpKey]                            BIGINT             NULL,
    [ArrestedChargedArsonCount]                                                      INT                NULL,
    [ArrestedChargedArsonCountDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [ArrestedChargedRapeCount]                                                       INT                NULL,
    [ArrestedChargedRapeCountDensAsiNonResponseLkpKey]                               BIGINT             NULL,
    [ArrestedChargedHomicideManslaughterCount]                                       INT                NULL,
    [ArrestedChargedHomicideManslaughterCountDensAsiNonResponseLkpKey]               BIGINT             NULL,
    [ArrestedChargedProstitutionCount]                                               INT                NULL,
    [ArrestedChargedProstitutionCountDensAsiNonResponseLkpKey]                       BIGINT             NULL,
    [ArrestedChargedContemptOfCountCount]                                            INT                NULL,
    [ArrestedChargedContemptOfCountCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [ArrestedChargedOtherCount]                                                      INT                NULL,
    [ArrestedChargedOtherCountDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [ArrestChargesResultedInConvictionsCount]                                        INT                NULL,
    [ArrestChargesResultedInConvictionsCountDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [ChargedWithDisorderlyConductCount]                                              INT                NULL,
    [ChargedWithDisorderlyConductCountDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [ChargedWithDrivingWhileIntoxicatedCount]                                        INT                NULL,
    [ChargedWithDrivingWhileIntoxicatedCountDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [ChargedWithMajorDrivingViolationsCount]                                         INT                NULL,
    [ChargedWithMajorDrivingViolationsCountDensAsiNonResponseLkpKey]                 BIGINT             NULL,
    [IncarcerationInLifeMonthCount]                                                  INT                NULL,
    [IncarcerationInLifeMonthCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [LastIncarcerationLengthMonthCount]                                              INT                NULL,
    [LastIncarcerationLengthMonthCountDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [IncarcerationForDensAsiViolationTypeLkpKey]                                     BIGINT             NULL,
    [IncarcerationForDensAsiViolationTypeDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [PresentlyAwaitingChargesIndicator]                                              BIT                NULL,
    [PresentlyAwaitingChargesIndicatorDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [PresentlyAwaitingChargesForDensAsiViolationTypeLkpKey]                          BIGINT             NULL,
    [PresentlyAwaitingChargesForDensAsiViolationTypeDensAsiNonResponseLkpKey]        BIGINT             NULL,
    [IncarceratedInLastThirtyDaysDayCount]                                           INT                NULL,
    [IncarceratedInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [IllegalActivityInLastThirtyDaysDayCount]                                        INT                NULL,
    [IllegalActivityInLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [SeriousnessOfLegalProblemsDensAsiPatientRatingLkpKey]                           BIGINT             NULL,
    [SeriousnessOfLegalProblemsDensAsiPatientRatingDensAsiNonResponseLkpKey]         BIGINT             NULL,
    [ImportanceOfLegalProblemCounselingDensAsiPatientRatingLkpKey]                   BIGINT             NULL,
    [ImportanceOfLegalProblemCounselingDensAsiPatientRatingDensAsiNonResponseLkpKey] BIGINT             NULL,
    [TreatmentMandatoryForCriminalJusticeSystemIndicator]                            BIT                NULL,
    [TreatmentMandatoryForCriminalJusticeSystemIndicatorDensAsiNonResponseLkpKey]    BIGINT             NULL,
    [TreatmentInsteadOfIncarcerationInPrisonIndicator]                               BIT                NULL,
    [TreatmentInsteadOfIncarcerationInPrisonIndicatorDensAsiNonResponseLkpKey]       BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([DensAsiInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





