CREATE TABLE [DensAsiModule].[DensAsiPsychiatricStatus] (
    [DensAsiInterviewKey]                                                                    BIGINT             NOT NULL,
    [CreatedTimestamp]                                                                       DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                                       DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                                              BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                                              BIGINT             NOT NULL,
    [PsychologicalTreatmentInHospitalCountNote]                                              NVARCHAR (MAX)     NULL,
    [PsychologicalTreatmentAsOutpatientCountNote]                                            NVARCHAR (MAX)     NULL,
    [PsychiatricDisabilityPensionIndicatorNote]                                              NVARCHAR (MAX)     NULL,
    [DepressionNote]                                                                         NVARCHAR (MAX)     NULL,
    [AnxietyNote]                                                                            NVARCHAR (MAX)     NULL,
    [HallucinationNote]                                                                      NVARCHAR (MAX)     NULL,
    [TroubleConcentratingNote]                                                               NVARCHAR (MAX)     NULL,
    [TroubleControllingRageNote]                                                             NVARCHAR (MAX)     NULL,
    [ThoughtsOfSuicideNote]                                                                  NVARCHAR (MAX)     NULL,
    [AttemptedSuicideNote]                                                                   NVARCHAR (MAX)     NULL,
    [PrescribedMedicationsNote]                                                              NVARCHAR (MAX)     NULL,
    [PsychologicalProblemsLastThirtyDaysDayCountNote]                                        NVARCHAR (MAX)     NULL,
    [TroubledByPsychologicalProblemsDensAsiPatientRatingNote]                                NVARCHAR (MAX)     NULL,
    [ImportanceOfPsychologicalProblemCounselingDensAsiPatientRatingNote]                     NVARCHAR (MAX)     NULL,
    [PatientDepressedIndicatorNote]                                                          NVARCHAR (MAX)     NULL,
    [PatientHostileIndicatorNote]                                                            NVARCHAR (MAX)     NULL,
    [PatientAnxiousIndicatorNote]                                                            NVARCHAR (MAX)     NULL,
    [PatientParanoidIndicatorNote]                                                           NVARCHAR (MAX)     NULL,
    [PatientTroubleConcentratingIndicatorNote]                                               NVARCHAR (MAX)     NULL,
    [PatientThoughtsOfSuicideIndicatorNote]                                                  NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingNote]                                          NVARCHAR (MAX)     NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicator]                                 BIT                NULL,
    [ConfidenceDistortedByPatientMisrepresentationIndicatorNote]                             NVARCHAR (MAX)     NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicator]                         BIT                NULL,
    [ConfidenceRateDistortedByPatientInabilityToUnderstandIndicatorNote]                     NVARCHAR (MAX)     NULL,
    [SectionNote]                                                                            NVARCHAR (MAX)     NULL,
    [HorribleExperiencesIndicatorNote]                                                       NVARCHAR (MAX)     NULL,
    [NightmaresLastThirtyDaysDensAsiPatientRatingNote]                                       NVARCHAR (MAX)     NULL,
    [TraumaticEventThoughtsLastThirtyDaysDensAsiPatientRatingNote]                           NVARCHAR (MAX)     NULL,
    [OnGuardLastThirtyDaysDensAsiPatientRatingNote]                                          NVARCHAR (MAX)     NULL,
    [FeltNumbLastThirtyDaysDensAsiPatientRatingNote]                                         NVARCHAR (MAX)     NULL,
    [PatientCounselingDensAsiInterviewerRatingLkpKey]                                        BIGINT             NULL,
    [PsychologicalTreatmentInHospitalCount]                                                  INT                NULL,
    [PsychologicalTreatmentInHospitalCountDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [PsychologicalTreatmentAsOutpatientCount]                                                INT                NULL,
    [PsychologicalTreatmentAsOutpatientCountDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [PsychiatricDisabilityPensionIndicator]                                                  BIT                NULL,
    [PsychiatricDisabilityPensionIndicatorDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [DepressionLastThirtyDaysIndicator]                                                      BIT                NULL,
    [DepressionLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [DepressionLifetimeIndicator]                                                            BIT                NULL,
    [DepressionLifetimeIndicatorDensAsiNonResponseLkpKey]                                    BIGINT             NULL,
    [AnxietyLastThirtyDaysIndicator]                                                         BIT                NULL,
    [AnxietyLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                                 BIGINT             NULL,
    [AnxietyLifetimeIndicator]                                                               BIT                NULL,
    [AnxietyLifetimeIndicatorDensAsiNonResponseLkpKey]                                       BIGINT             NULL,
    [HallucinationLastThirtyDaysIndicator]                                                   BIT                NULL,
    [HallucinationLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [HallucinationLifetimeIndicator]                                                         BIT                NULL,
    [HallucinationLifetimeIndicatorDensAsiNonResponseLkpKey]                                 BIGINT             NULL,
    [TroubleConcentratingLastThirtyDaysIndicator]                                            BIT                NULL,
    [TroubleConcentratingLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [TroubleConcentratingLifetimeIndicator]                                                  BIT                NULL,
    [TroubleConcentratingLifetimeIndicatorDensAsiNonResponseLkpKey]                          BIGINT             NULL,
    [TroubleControllingRageLastThirtyDaysIndicator]                                          BIT                NULL,
    [TroubleControllingRageLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                  BIGINT             NULL,
    [TroubleControllingRageLifetimeIndicator]                                                BIT                NULL,
    [TroubleControllingRageLifetimeIndicatorDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [ThoughtsOfSuicideLastThirtyDaysIndicator]                                               BIT                NULL,
    [ThoughtsOfSuicideLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                       BIGINT             NULL,
    [ThoughtsOfSuicideLifetimeIndicator]                                                     BIT                NULL,
    [ThoughtsOfSuicideLifetimeIndicatorDensAsiNonResponseLkpKey]                             BIGINT             NULL,
    [AttemptedSuicideLastThirtyDaysIndicator]                                                BIT                NULL,
    [AttemptedSuicideLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                        BIGINT             NULL,
    [AttemptedSuicideLifetimeIndicator]                                                      BIT                NULL,
    [AttemptedSuicideLifetimeIndicatorDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [PrescribedMedicationsLastThirtyDaysIndicator]                                           BIT                NULL,
    [PrescribedMedicationsLastThirtyDaysIndicatorDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [PrescribedMedicationsLifetimeIndicator]                                                 BIT                NULL,
    [PrescribedMedicationsLifetimeIndicatorDensAsiNonResponseLkpKey]                         BIGINT             NULL,
    [PsychologicalProblemsLastThirtyDaysDayCount]                                            INT                NULL,
    [PsychologicalProblemsLastThirtyDaysDayCountDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [TroubledByPsychologicalProblemsDensAsiPatientRatingLkpKey]                              BIGINT             NULL,
    [TroubledByPsychologicalProblemsDensAsiPatientRatingDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [ImportanceOfPsychologicalProblemCounselingDensAsiPatientRatingLkpKey]                   BIGINT             NULL,
    [ImportanceOfPsychologicalProblemCounselingDensAsiPatientRatingDensAsiNonResponseLkpKey] BIGINT             NULL,
    [PatientDepressedIndicator]                                                              BIT                NULL,
    [PatientDepressedIndicatorDensAsiNonResponseLkpKey]                                      BIGINT             NULL,
    [PatientHostileIndicator]                                                                BIT                NULL,
    [PatientHostileIndicatorDensAsiNonResponseLkpKey]                                        BIGINT             NULL,
    [PatientAnxiousIndicator]                                                                BIT                NULL,
    [PatientAnxiousIndicatorDensAsiNonResponseLkpKey]                                        BIGINT             NULL,
    [PatientParanoidIndicator]                                                               BIT                NULL,
    [PatientParanoidIndicatorDensAsiNonResponseLkpKey]                                       BIGINT             NULL,
    [PatientTroubleConcentratingIndicator]                                                   BIT                NULL,
    [PatientTroubleConcentratingIndicatorDensAsiNonResponseLkpKey]                           BIGINT             NULL,
    [PatientThoughtsOfSuicideIndicator]                                                      BIT                NULL,
    [PatientThoughtsOfSuicideIndicatorDensAsiNonResponseLkpKey]                              BIGINT             NULL,
    [HorribleExperiencesIndicator]                                                           BIT                NULL,
    [HorribleExperiencesIndicatorDensAsiNonResponseLkpKey]                                   BIGINT             NULL,
    [NightmaresLastThirtyDaysDensAsiPatientRatingLkpKey]                                     BIGINT             NULL,
    [NightmaresLastThirtyDaysDensAsiPatientRatingDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [TraumaticEventThoughtsLastThirtyDaysDensAsiPatientRatingLkpKey]                         BIGINT             NULL,
    [TraumaticEventThoughtsLastThirtyDaysDensAsiPatientRatingDensAsiNonResponseLkpKey]       BIGINT             NULL,
    [OnGuardLastThirtyDaysDensAsiPatientRatingLkpKey]                                        BIGINT             NULL,
    [OnGuardLastThirtyDaysDensAsiPatientRatingDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [FeltNumbLastThirtyDaysDensAsiPatientRatingLkpKey]                                       BIGINT             NULL,
    [FeltNumbLastThirtyDaysDensAsiPatientRatingDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([DensAsiInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





