CREATE TABLE [DensAsiModule].[DensAsiDsmIv] (
    [DensAsiInterviewKey]                                                          BIGINT             NOT NULL,
    [CreatedTimestamp]                                                             DATETIMEOFFSET (7) NOT NULL,
    [UpdatedTimestamp]                                                             DATETIMEOFFSET (7) NOT NULL,
    [CreatedBySystemAccountKey]                                                    BIGINT             NOT NULL,
    [UpdatedBySystemAccountKey]                                                    BIGINT             NOT NULL,
    [LessEffectIndicatorNote]                                                      NVARCHAR (MAX)     NULL,
    [PhysicalDistressOnQuittingNote]                                               NVARCHAR (MAX)     NULL,
    [UsedMoreIndicatorNote]                                                        NVARCHAR (MAX)     NULL,
    [WantedToCutDownIndicatorNote]                                                 NVARCHAR (MAX)     NULL,
    [TimeSpentObtainingIndicatorNote]                                              NVARCHAR (MAX)     NULL,
    [GiveUpWorkFamilyActivitiesIndicatorNote]                                      NVARCHAR (MAX)     NULL,
    [ContinuedToUseIndicatorNote]                                                  NVARCHAR (MAX)     NULL,
    [SectionNote]                                                                  NVARCHAR (MAX)     NULL,
    [InabilityToMeetResponsibilitiesIndicatorNote]                                 NVARCHAR (MAX)     NULL,
    [VoluntaryPhysicalDangerIndicatorNote]                                         NVARCHAR (MAX)     NULL,
    [LegalProblemsIndicatorNote]                                                   NVARCHAR (MAX)     NULL,
    [SocialProblemsIndicatorNote]                                                  NVARCHAR (MAX)     NULL,
    [AlcoholDependenceLessEffectIndicator]                                         BIT                NULL,
    [AlcoholDependenceLessEffectIndicatorDensAsiNonResponseLkpKey]                 BIGINT             NULL,
    [DrugDependenceLessEffectIndicator]                                            BIT                NULL,
    [DrugDependenceLessEffectIndicatorDensAsiNonResponseLkpKey]                    BIGINT             NULL,
    [AlcoholDependencePhysicalDistressOnQuittingIndicator]                         BIT                NULL,
    [AlcoholDependencePhysicalDistressOnQuittingIndicatorDensAsiNonResponseLkpKey] BIGINT             NULL,
    [DrugDependencePhysicalDistressOnQuittingIndicator]                            BIT                NULL,
    [DrugDependencePhysicalDistressOnQuittingIndicatorDensAsiNonResponseLkpKey]    BIGINT             NULL,
    [AlcoholDependenceUsedMoreIndicator]                                           BIT                NULL,
    [AlcoholDependenceUsedMoreIndicatorDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [DrugDependenceUsedMoreIndicator]                                              BIT                NULL,
    [DrugDependenceUsedMoreIndicatorDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [AlcoholDependenceWantedToCutDownIndicator]                                    BIT                NULL,
    [AlcoholDependenceWantedToCutDownIndicatorDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [DrugDependenceWantedToCutDownIndicator]                                       BIT                NULL,
    [DrugDependenceWantedToCutDownIndicatorDensAsiNonResponseLkpKey]               BIGINT             NULL,
    [AlcoholDependenceTimeSpentObtainingIndicator]                                 BIT                NULL,
    [AlcoholDependenceTimeSpentObtainingIndicatorDensAsiNonResponseLkpKey]         BIGINT             NULL,
    [DrugDependenceTimeSpentObtainingIndicator]                                    BIT                NULL,
    [DrugDependenceTimeSpentObtainingIndicatorDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [AlcoholDependenceGiveUpWorkFamilyActivitiesIndicator]                         BIT                NULL,
    [AlcoholDependenceGiveUpWorkFamilyActivitiesIndicatorDensAsiNonResponseLkpKey] BIGINT             NULL,
    [DrugDependenceGiveUpWorkFamilyActivitiesIndicator]                            BIT                NULL,
    [DrugDependenceGiveUpWorkFamilyActivitiesIndicatorDensAsiNonResponseLkpKey]    BIGINT             NULL,
    [AlcoholDependenceContinuedToUseIndicator]                                     BIT                NULL,
    [AlcoholDependenceContinuedToUseIndicatorDensAsiNonResponseLkpKey]             BIGINT             NULL,
    [DrugDependenceContinuedToUseIndicator]                                        BIT                NULL,
    [DrugDependenceContinuedToUseIndicatorDensAsiNonResponseLkpKey]                BIGINT             NULL,
    [AlcoholAbuseInabilityToMeetResponsibilitiesIndicator]                         BIT                NULL,
    [AlcoholAbuseInabilityToMeetResponsibilitiesIndicatorDensAsiNonResponseLkpKey] BIGINT             NULL,
    [DrugAbuseInabilityToMeetResponsibilitiesIndicator]                            BIT                NULL,
    [DrugAbuseInabilityToMeetResponsibilitiesIndicatorDensAsiNonResponseLkpKey]    BIGINT             NULL,
    [AlcoholAbuseVoluntaryPhysicalDangerIndicator]                                 BIT                NULL,
    [AlcoholAbuseVoluntaryPhysicalDangerIndicatorDensAsiNonResponseLkpKey]         BIGINT             NULL,
    [DrugAbuseVoluntaryPhysicalDangerIndicator]                                    BIT                NULL,
    [DrugAbuseVoluntaryPhysicalDangerIndicatorDensAsiNonResponseLkpKey]            BIGINT             NULL,
    [AlcoholAbuseLegalProblemsIndicator]                                           BIT                NULL,
    [AlcoholAbuseLegalProblemsIndicatorDensAsiNonResponseLkpKey]                   BIGINT             NULL,
    [DrugAbuseLegalProblemsIndicator]                                              BIT                NULL,
    [DrugAbuseLegalProblemsIndicatorDensAsiNonResponseLkpKey]                      BIGINT             NULL,
    [AlcoholAbuseSocialProblemsIndicator]                                          BIT                NULL,
    [AlcoholAbuseSocialProblemsIndicatorDensAsiNonResponseLkpKey]                  BIGINT             NULL,
    [DrugAbuseSocialProblemsIndicator]                                             BIT                NULL,
    [DrugAbuseSocialProblemsIndicatorDensAsiNonResponseLkpKey]                     BIGINT             NULL,
    PRIMARY KEY CLUSTERED ([DensAsiInterviewKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);





